export type AdvanceTax = {
  accountHead: string | null;
  allocatedAmount: number | null;
  createdAt: Date;
  creation: Date | null;
  docstatus: number | null;
  id: string;
  idx: number | null;
  modified: Date | null;
  modifiedBy: string | null;
  name: string | null;
  owner: string | null;
  parent: string | null;
  parentfield: string | null;
  parenttype: string | null;
  referenceDetail: string | null;
  referenceName: string | null;
  referenceType: string | null;
  updatedAt: Date;
};
