export type PosClosingEntryDetail = {
  closingAmount: number | null;
  createdAt: Date;
  creation: Date | null;
  difference: number | null;
  docStatus: number | null;
  expectedAmount: number | null;
  id: string;
  idx: number | null;
  modeOfPayment: string | null;
  modified: Date | null;
  modifiedBy: string | null;
  name: string | null;
  openingAmount: number | null;
  owner: string | null;
  parent: string | null;
  parentField: string | null;
  parentType: string | null;
  updatedAt: Date;
};
