export type Contact = {
  address: string | null;
  companyName: string | null;
  createdAt: Date;
  creation: Date | null;
  department: string | null;
  designation: string | null;
  docstatus: number | null;
  emailId: string | null;
  firstName: string | null;
  fullName: string | null;
  gender: string | null;
  googleContacts: string | null;
  googleContactsId: string | null;
  id: string;
  idx: number | null;
  image: string | null;
  isPrimaryContact: boolean | null;
  lastName: string | null;
  middleName: string | null;
  mobileNo: string | null;
  modified: Date | null;
  modifiedBy: string | null;
  name: string | null;
  owner: string | null;
  phone: string | null;
  pulledFromGoogleContacts: boolean | null;
  salutation: string | null;
  status: string | null;
  syncWithGoogleContacts: boolean | null;
  unsubscribed: boolean | null;
  updatedAt: Date;
  user: string | null;
};
