export type AssetCapitalizationServiceItem = {
  actualQty: number | null;
  amount: number | null;
  batchNo: string | null;
  costCenter: string | null;
  createdAt: Date;
  creation: Date | null;
  docstatus: number | null;
  expenseAccount: string | null;
  id: string;
  idx: number | null;
  itemCode: string | null;
  itemName: string | null;
  modified: Date | null;
  modifiedBy: string | null;
  name: string | null;
  owner: string | null;
  parent: string | null;
  parentField: string | null;
  parentType: string | null;
  parentfield: string | null;
  parenttype: string | null;
  qty: number | null;
  rate: number | null;
  serialAndBatchBundle: string | null;
  serialNo: string | null;
  stockQty: number | null;
  stockUom: string | null;
  uom: string | null;
  updatedAt: Date;
  useSerialBatchFields: number | null;
  valuationRate: number | null;
  warehouse: string | null;
};
