import { StringNullableFilter } from "../../util/StringNullableFilter";
import { FloatNullableFilter } from "../../util/FloatNullableFilter";
import { DateTimeNullableFilter } from "../../util/DateTimeNullableFilter";
import { IntNullableFilter } from "../../util/IntNullableFilter";
import { StringFilter } from "../../util/StringFilter";

export type AssetCapitalizationWhereInput = {
  amendedFrom?: StringNullableFilter;
  assetItemsTotal?: FloatNullableFilter;
  capitalizationMethod?: StringNullableFilter;
  company?: StringNullableFilter;
  costCenter?: StringNullableFilter;
  creation?: DateTimeNullableFilter;
  docstatus?: IntNullableFilter;
  entryType?: StringNullableFilter;
  financeBook?: StringNullableFilter;
  id?: StringFilter;
  idx?: IntNullableFilter;
  modified?: DateTimeNullableFilter;
  modifiedBy?: StringNullableFilter;
  name?: StringNullableFilter;
  namingSeries?: StringNullableFilter;
  owner?: StringNullableFilter;
  postingDate?: DateTimeNullableFilter;
  postingTime?: DateTimeNullableFilter;
  serviceItemsTotal?: FloatNullableFilter;
  setPostingTime?: IntNullableFilter;
  stockItemsTotal?: FloatNullableFilter;
  targetAsset?: StringNullableFilter;
  targetAssetLocation?: StringNullableFilter;
  targetAssetName?: StringNullableFilter;
  targetBatchNo?: StringNullableFilter;
  targetFixedAssetAccount?: StringNullableFilter;
  targetHasBatchNo?: IntNullableFilter;
  targetHasSerialNo?: IntNullableFilter;
  targetIncomingRate?: FloatNullableFilter;
  targetIsFixedAsset?: IntNullableFilter;
  targetItemCode?: StringNullableFilter;
  targetItemName?: StringNullableFilter;
  targetQty?: FloatNullableFilter;
  targetSerialNo?: StringNullableFilter;
  targetStockUom?: StringNullableFilter;
  targetWarehouse?: StringNullableFilter;
  title?: StringNullableFilter;
  totalValue?: FloatNullableFilter;
};
