import { SortOrder } from "../../util/SortOrder";

export type AssetCapitalizationOrderByInput = {
  amendedFrom?: SortOrder;
  assetItemsTotal?: SortOrder;
  capitalizationMethod?: SortOrder;
  company?: SortOrder;
  costCenter?: SortOrder;
  createdAt?: SortOrder;
  creation?: SortOrder;
  docstatus?: SortOrder;
  entryType?: SortOrder;
  financeBook?: SortOrder;
  id?: SortOrder;
  idx?: SortOrder;
  modified?: SortOrder;
  modifiedBy?: SortOrder;
  name?: SortOrder;
  namingSeries?: SortOrder;
  owner?: SortOrder;
  postingDate?: SortOrder;
  postingTime?: SortOrder;
  serviceItemsTotal?: SortOrder;
  setPostingTime?: SortOrder;
  stockItemsTotal?: SortOrder;
  targetAsset?: SortOrder;
  targetAssetLocation?: SortOrder;
  targetAssetName?: SortOrder;
  targetBatchNo?: SortOrder;
  targetFixedAssetAccount?: SortOrder;
  targetHasBatchNo?: SortOrder;
  targetHasSerialNo?: SortOrder;
  targetIncomingRate?: SortOrder;
  targetIsFixedAsset?: SortOrder;
  targetItemCode?: SortOrder;
  targetItemName?: SortOrder;
  targetQty?: SortOrder;
  targetSerialNo?: SortOrder;
  targetStockUom?: SortOrder;
  targetWarehouse?: SortOrder;
  title?: SortOrder;
  totalValue?: SortOrder;
  updatedAt?: SortOrder;
};
