import { SortOrder } from "../../util/SortOrder";

export type StockReconciliationItemOrderByInput = {
  allowZeroValuationRate?: SortOrder;
  amount?: SortOrder;
  amountDifference?: SortOrder;
  barcode?: SortOrder;
  batchNo?: SortOrder;
  createdAt?: SortOrder;
  creation?: SortOrder;
  currentAmount?: SortOrder;
  currentQty?: SortOrder;
  currentSerialAndBatchBundle?: SortOrder;
  currentSerialNo?: SortOrder;
  currentValuationRate?: SortOrder;
  docstatus?: SortOrder;
  hasItemScanned?: SortOrder;
  id?: SortOrder;
  idx?: SortOrder;
  itemCode?: SortOrder;
  itemGroup?: SortOrder;
  itemName?: SortOrder;
  modified?: SortOrder;
  modifiedBy?: SortOrder;
  name?: SortOrder;
  owner?: SortOrder;
  parent?: SortOrder;
  parentfield?: SortOrder;
  parenttype?: SortOrder;
  qty?: SortOrder;
  quantityDifference?: SortOrder;
  reconcileAllSerialBatch?: SortOrder;
  serialAndBatchBundle?: SortOrder;
  serialNo?: SortOrder;
  updatedAt?: SortOrder;
  useSerialBatchFields?: SortOrder;
  valuationRate?: SortOrder;
  warehouse?: SortOrder;
};
