export type StockReconciliationItem = {
  allowZeroValuationRate: boolean | null;
  amount: number | null;
  amountDifference: number | null;
  barcode: string | null;
  batchNo: string | null;
  createdAt: Date;
  creation: Date | null;
  currentAmount: number | null;
  currentQty: number | null;
  currentSerialAndBatchBundle: string | null;
  currentSerialNo: string | null;
  currentValuationRate: number | null;
  docstatus: number | null;
  hasItemScanned: string | null;
  id: string;
  idx: number | null;
  itemCode: string | null;
  itemGroup: string | null;
  itemName: string | null;
  modified: Date | null;
  modifiedBy: string | null;
  name: string | null;
  owner: string | null;
  parent: string | null;
  parentfield: string | null;
  parenttype: string | null;
  qty: number | null;
  quantityDifference: string | null;
  reconcileAllSerialBatch: boolean | null;
  serialAndBatchBundle: string | null;
  serialNo: string | null;
  updatedAt: Date;
  useSerialBatchFields: boolean | null;
  valuationRate: number | null;
  warehouse: string | null;
};
