import { StringNullableFilter } from "../../util/StringNullableFilter";
import { DateTimeNullableFilter } from "../../util/DateTimeNullableFilter";
import { IntNullableFilter } from "../../util/IntNullableFilter";
import { StringFilter } from "../../util/StringFilter";

export type CommunicationWhereInput = {
  bcc?: StringNullableFilter;
  cc?: StringNullableFilter;
  commentType?: StringNullableFilter;
  communicationDate?: DateTimeNullableFilter;
  communicationMedium?: StringNullableFilter;
  communicationType?: StringNullableFilter;
  content?: StringNullableFilter;
  creation?: DateTimeNullableFilter;
  deliveryStatus?: StringNullableFilter;
  docstatus?: IntNullableFilter;
  emailAccount?: StringNullableFilter;
  emailStatus?: StringNullableFilter;
  emailTemplate?: StringNullableFilter;
  feedbackRequest?: StringNullableFilter;
  hasAttachment?: IntNullableFilter;
  id?: StringFilter;
  idx?: IntNullableFilter;
  imapFolder?: StringNullableFilter;
  inReplyTo?: StringNullableFilter;
  messageId?: StringNullableFilter;
  modified?: DateTimeNullableFilter;
  modifiedBy?: StringNullableFilter;
  owner?: StringNullableFilter;
  phoneNo?: StringNullableFilter;
  rating?: IntNullableFilter;
  readByRecipient?: IntNullableFilter;
  readByRecipientOn?: DateTimeNullableFilter;
  readReceipt?: IntNullableFilter;
  recipients?: StringNullableFilter;
  referenceDoctype?: StringNullableFilter;
  referenceName?: StringNullableFilter;
  referenceOwner?: StringNullableFilter;
  seen?: IntNullableFilter;
  sendAfter?: DateTimeNullableFilter;
  sender?: StringNullableFilter;
  senderFullName?: StringNullableFilter;
  sentOrReceived?: StringNullableFilter;
  status?: StringNullableFilter;
  subject?: StringNullableFilter;
  textContent?: StringNullableFilter;
  uid?: IntNullableFilter;
  unreadNotificationSent?: IntNullableFilter;
  user?: StringNullableFilter;
  userTags?: StringNullableFilter;
};
