export type Communication = {
  bcc: string | null;
  cc: string | null;
  commentType: string | null;
  communicationDate: Date | null;
  communicationMedium: string | null;
  communicationType: string | null;
  content: string | null;
  createdAt: Date;
  creation: Date | null;
  deliveryStatus: string | null;
  docstatus: number | null;
  emailAccount: string | null;
  emailStatus: string | null;
  emailTemplate: string | null;
  feedbackRequest: string | null;
  hasAttachment: number | null;
  id: string;
  idx: number | null;
  imapFolder: string | null;
  inReplyTo: string | null;
  messageId: string | null;
  modified: Date | null;
  modifiedBy: string | null;
  owner: string | null;
  phoneNo: string | null;
  rating: number | null;
  readByRecipient: number | null;
  readByRecipientOn: Date | null;
  readReceipt: number | null;
  recipients: string | null;
  referenceDoctype: string | null;
  referenceName: string | null;
  referenceOwner: string | null;
  seen: number | null;
  sendAfter: Date | null;
  sender: string | null;
  senderFullName: string | null;
  sentOrReceived: string | null;
  status: string | null;
  subject: string | null;
  textContent: string | null;
  uid: number | null;
  unreadNotificationSent: number | null;
  updatedAt: Date;
  user: string | null;
  userTags: string | null;
};
