export type CariCagDcshBlCntrCreateInput = {
  cagMgmtNo?: string | null;
  cntrNo?: string | null;
  cntrSrno?: number | null;
  cntrTpCd?: string | null;
  delYn?: string | null;
  ecntrWght?: number | null;
  frstRegstId?: string | null;
  frstRgsrDttm?: Date | null;
  lastChgDttm?: Date | null;
  lastChprId?: string | null;
  mrn?: string | null;
  pckgGcnt?: number | null;
  pckgUtCd?: string | null;
  sealChpn1?: string | null;
  sealChpn2?: string | null;
  sealChpn3?: string | null;
  sealNo1?: string | null;
  sealNo2?: string | null;
  sealNo3?: string | null;
  ttwg?: number | null;
};
