export type BomWebsiteItem = {
  createdAt: Date;
  creation: Date | null;
  description: string | null;
  docstatus: number | null;
  id: string;
  idx: number | null;
  itemCode: string | null;
  itemName: string | null;
  modified: Date | null;
  modifiedBy: string | null;
  name: string | null;
  owner: string | null;
  parent: string | null;
  parentfield: string | null;
  parenttype: string | null;
  qty: number | null;
  updatedAt: Date;
  websiteImage: string | null;
};
