export type MaintenanceScheduleItemCreateInput = {
  creation?: Date | null;
  description?: string | null;
  docstatus?: number | null;
  endDate?: Date | null;
  idx?: number | null;
  itemCode?: string | null;
  itemName?: string | null;
  modified?: Date | null;
  modifiedBy?: string | null;
  name?: string | null;
  noOfVisits?: number | null;
  owner?: string | null;
  parent?: string | null;
  parentfield?: string | null;
  parenttype?: string | null;
  periodicity?: string | null;
  salesOrder?: string | null;
  salesPerson?: string | null;
  serialAndBatchBundle?: string | null;
  serialNo?: string | null;
  startDate?: Date | null;
};
