export type SalesInvoiceTimesheet = {
  activityType: string | null;
  billingAmount: number | null;
  billingHours: number | null;
  createdAt: Date;
  creation: Date | null;
  description: string | null;
  docstatus: number | null;
  fromTime: Date | null;
  id: string;
  idx: number | null;
  modified: Date | null;
  modifiedBy: string | null;
  name: string | null;
  owner: string | null;
  parent: string | null;
  parentField: string | null;
  parentType: string | null;
  projectName: string | null;
  timeSheet: string | null;
  timesheetDetail: string | null;
  toTime: Date | null;
  updatedAt: Date;
};
