import { DateTimeNullableFilter } from "../../util/DateTimeNullableFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { IntNullableFilter } from "../../util/IntNullableFilter";
import { FloatNullableFilter } from "../../util/FloatNullableFilter";
import { StringFilter } from "../../util/StringFilter";

export type JobCardWhereInput = {
  actualEndDate?: DateTimeNullableFilter;
  actualStartDate?: DateTimeNullableFilter;
  amendedFrom?: StringNullableFilter;
  barcode?: StringNullableFilter;
  batchNo?: StringNullableFilter;
  bomNo?: StringNullableFilter;
  company?: StringNullableFilter;
  creation?: DateTimeNullableFilter;
  currentTime?: IntNullableFilter;
  docstatus?: IntNullableFilter;
  expectedEndDate?: DateTimeNullableFilter;
  expectedStartDate?: DateTimeNullableFilter;
  forJobCard?: StringNullableFilter;
  forOperation?: StringNullableFilter;
  forQuantity?: FloatNullableFilter;
  hourRate?: FloatNullableFilter;
  id?: StringFilter;
  idx?: IntNullableFilter;
  isCorrectiveJobCard?: IntNullableFilter;
  itemName?: StringNullableFilter;
  jobStarted?: IntNullableFilter;
  modified?: DateTimeNullableFilter;
  modifiedBy?: StringNullableFilter;
  name?: StringNullableFilter;
  namingSeries?: StringNullableFilter;
  operation?: StringNullableFilter;
  operationId?: StringNullableFilter;
  operationRowNumber?: StringNullableFilter;
  owner?: StringNullableFilter;
  postingDate?: DateTimeNullableFilter;
  processLossQty?: FloatNullableFilter;
  productionItem?: StringNullableFilter;
  project?: StringNullableFilter;
  qualityInspection?: StringNullableFilter;
  qualityInspectionTemplate?: StringNullableFilter;
  remarks?: StringNullableFilter;
  requestedQty?: FloatNullableFilter;
  sequenceId?: IntNullableFilter;
  serialAndBatchBundle?: StringNullableFilter;
  serialNo?: StringNullableFilter;
  startedTime?: DateTimeNullableFilter;
  status?: StringNullableFilter;
  timeRequired?: FloatNullableFilter;
  totalCompletedQty?: FloatNullableFilter;
  totalTimeInMins?: FloatNullableFilter;
  transferredQty?: FloatNullableFilter;
  wipWarehouse?: StringNullableFilter;
  workOrder?: StringNullableFilter;
  workstation?: StringNullableFilter;
  workstationType?: StringNullableFilter;
};
