export type InstallationNoteItem = {
  createdAt: Date;
  description: string | null;
  docstatus: number | null;
  id: string;
  idx: number | null;
  itemCode: string | null;
  name: string | null;
  owner: string | null;
  parent: string | null;
  parentfield: string | null;
  parenttype: string | null;
  prevdocDetailDocname: string | null;
  prevdocDocname: string | null;
  prevdocDoctype: string | null;
  qty: number | null;
  serialAndBatchBundle: string | null;
  serialNo: string | null;
  updatedAt: Date;
};
