export type SalesTeam = {
  allocatedAmount: number | null;
  allocatedPercentage: number | null;
  commissionRate: string | null;
  contactNo: string | null;
  createdAt: Date;
  creation: Date | null;
  docstatus: number | null;
  id: string;
  idx: number | null;
  incentives: number | null;
  modified: Date | null;
  modifiedBy: string | null;
  name: string | null;
  owner: string | null;
  parent: string | null;
  parentField: string | null;
  parentType: string | null;
  salesPerson: string | null;
  updatedAt: Date;
};
