import { FloatNullableFilter } from "../../util/FloatNullableFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { DateTimeNullableFilter } from "../../util/DateTimeNullableFilter";
import { StringFilter } from "../../util/StringFilter";
import { IntNullableFilter } from "../../util/IntNullableFilter";

export type ClreDedVlutComnWhereInput = {
  cachAmt?: FloatNullableFilter;
  cachCurrCd?: StringNullableFilter;
  cachFxrt?: FloatNullableFilter;
  cachNcyAmt?: FloatNullableFilter;
  ddctAmt?: FloatNullableFilter;
  ddctCurrCd?: StringNullableFilter;
  ddctFxrt?: FloatNullableFilter;
  ddctNcyAmt?: FloatNullableFilter;
  ddctRt?: FloatNullableFilter;
  delYn?: StringNullableFilter;
  frstRegstId?: StringNullableFilter;
  frstRgsrDttm?: DateTimeNullableFilter;
  id?: StringFilter;
  infeeAmt?: FloatNullableFilter;
  infeeCurrCd?: StringNullableFilter;
  infeeFxrt?: FloatNullableFilter;
  infeeNcyAmt?: FloatNullableFilter;
  invcAmt?: FloatNullableFilter;
  invcCurrCd?: StringNullableFilter;
  invcFxrt?: FloatNullableFilter;
  invcNcyAmt?: FloatNullableFilter;
  invcUsdAmt?: FloatNullableFilter;
  lastChgDttm?: DateTimeNullableFilter;
  lastChprId?: StringNullableFilter;
  mdfyDgcnt?: IntNullableFilter;
  otcstAmt?: FloatNullableFilter;
  otcstCurrCd?: StringNullableFilter;
  otcstFxrt?: FloatNullableFilter;
  otcstNcyAmt?: FloatNullableFilter;
  reffNo?: StringNullableFilter;
  ttxbsNcyAmt?: FloatNullableFilter;
  ttxbsUsdAmt?: FloatNullableFilter;
  tvlutNcyAmt?: FloatNullableFilter;
  tvlutUsdAmt?: FloatNullableFilter;
};
