import { FloatNullableFilter } from "../../util/FloatNullableFilter";
import { BooleanNullableFilter } from "../../util/BooleanNullableFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { DateTimeNullableFilter } from "../../util/DateTimeNullableFilter";
import { IntNullableFilter } from "../../util/IntNullableFilter";
import { StringFilter } from "../../util/StringFilter";

export type StockLedgerEntryWhereInput = {
  actualQty?: FloatNullableFilter;
  autoCreatedSerialAndBatchBundle?: BooleanNullableFilter;
  batchNo?: StringNullableFilter;
  company?: StringNullableFilter;
  creation?: DateTimeNullableFilter;
  dependantSleVoucherDetailNo?: StringNullableFilter;
  docstatus?: IntNullableFilter;
  fiscalYear?: StringNullableFilter;
  hasBatchNo?: BooleanNullableFilter;
  hasSerialNo?: BooleanNullableFilter;
  id?: StringFilter;
  idx?: IntNullableFilter;
  incomingRate?: FloatNullableFilter;
  isAdjustmentEntry?: BooleanNullableFilter;
  isCancelled?: BooleanNullableFilter;
  itemCode?: StringNullableFilter;
  modified?: DateTimeNullableFilter;
  modifiedBy?: StringNullableFilter;
  name?: StringNullableFilter;
  outgoingRate?: FloatNullableFilter;
  owner?: StringNullableFilter;
  postingDate?: DateTimeNullableFilter;
  postingDatetime?: DateTimeNullableFilter;
  postingTime?: DateTimeNullableFilter;
  project?: StringNullableFilter;
  qtyAfterTransaction?: FloatNullableFilter;
  recalculateRate?: BooleanNullableFilter;
  serialAndBatchBundle?: StringNullableFilter;
  serialNo?: StringNullableFilter;
  stockQueue?: StringNullableFilter;
  stockUom?: StringNullableFilter;
  stockValue?: FloatNullableFilter;
  stockValueDifference?: FloatNullableFilter;
  toRename?: BooleanNullableFilter;
  valuationRate?: FloatNullableFilter;
  voucherDetailNo?: StringNullableFilter;
  voucherNo?: StringNullableFilter;
  voucherType?: StringNullableFilter;
  warehouse?: StringNullableFilter;
};
