export type AssetMovementItem = {
  asset: string | null;
  assetName: string | null;
  company: string | null;
  createdAt: Date;
  creation: Date | null;
  docstatus: number | null;
  fromEmployee: string | null;
  id: string;
  idx: number | null;
  modified: Date | null;
  modifiedBy: string | null;
  name: string | null;
  owner: string | null;
  parent: string | null;
  parentField: string | null;
  parentType: string | null;
  sourceLocation: string | null;
  targetLocation: string | null;
  toEmployee: string | null;
  updatedAt: Date;
};
