export type AssetMaintenanceLog = {
  actionsPerformed: string | null;
  amendedFrom: string | null;
  assetMaintenance: string | null;
  assetName: string | null;
  assignToName: string | null;
  certificateAttachement: string | null;
  completionDate: Date | null;
  createdAt: Date;
  creation: Date | null;
  description: string | null;
  docstatus: number | null;
  dueDate: Date | null;
  hasCertificate: number | null;
  id: string;
  idx: number | null;
  itemCode: string | null;
  itemName: string | null;
  maintenanceStatus: string | null;
  maintenanceType: string | null;
  modified: Date | null;
  modifiedBy: string | null;
  name: string | null;
  namingSeries: string | null;
  owner: string | null;
  periodicity: string | null;
  task: string | null;
  taskName: string | null;
  updatedAt: Date;
};
