import { SortOrder } from "../../util/SortOrder";

export type AreaTriggerCreatePropertyOrderByInput = {
  animId?: SortOrder;
  animKitId?: SortOrder;
  areaTriggerId?: SortOrder;
  createdAt?: SortOrder;
  decalPropertiesId?: SortOrder;
  facingCurveId?: SortOrder;
  flags?: SortOrder;
  id?: SortOrder;
  isAreatriggerCustom?: SortOrder;
  isCustom?: SortOrder;
  morphCurveId?: SortOrder;
  moveCurveId?: SortOrder;
  scaleCurveId?: SortOrder;
  scriptName?: SortOrder;
  shape?: SortOrder;
  shapeData0?: SortOrder;
  shapeData1?: SortOrder;
  shapeData2?: SortOrder;
  shapeData3?: SortOrder;
  shapeData4?: SortOrder;
  shapeData5?: SortOrder;
  shapeData6?: SortOrder;
  shapeData7?: SortOrder;
  timeToTarget?: SortOrder;
  timeToTargetScale?: SortOrder;
  updatedAt?: SortOrder;
  verifiedBuild?: SortOrder;
};
