/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { ItemAttributeService } from "../itemAttribute.service";
import { ItemAttributeCreateInput } from "./ItemAttributeCreateInput";
import { ItemAttribute } from "./ItemAttribute";
import { ItemAttributeFindManyArgs } from "./ItemAttributeFindManyArgs";
import { ItemAttributeWhereUniqueInput } from "./ItemAttributeWhereUniqueInput";
import { ItemAttributeUpdateInput } from "./ItemAttributeUpdateInput";

export class ItemAttributeControllerBase {
  constructor(protected readonly service: ItemAttributeService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: ItemAttribute })
  async createItemAttribute(
    @common.Body() data: ItemAttributeCreateInput
  ): Promise<ItemAttribute> {
    return await this.service.createItemAttribute({
      data: data,
      select: {
        attributeName: true,
        createdAt: true,
        docstatus: true,
        fromRange: true,
        id: true,
        idx: true,
        increment: true,
        modifiedBy: true,
        name: true,
        numericValues: true,
        owner: true,
        toRange: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [ItemAttribute] })
  @ApiNestedQuery(ItemAttributeFindManyArgs)
  async itemAttributes(
    @common.Req() request: Request
  ): Promise<ItemAttribute[]> {
    const args = plainToClass(ItemAttributeFindManyArgs, request.query);
    return this.service.itemAttributes({
      ...args,
      select: {
        attributeName: true,
        createdAt: true,
        docstatus: true,
        fromRange: true,
        id: true,
        idx: true,
        increment: true,
        modifiedBy: true,
        name: true,
        numericValues: true,
        owner: true,
        toRange: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: ItemAttribute })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async itemAttribute(
    @common.Param() params: ItemAttributeWhereUniqueInput
  ): Promise<ItemAttribute | null> {
    const result = await this.service.itemAttribute({
      where: params,
      select: {
        attributeName: true,
        createdAt: true,
        docstatus: true,
        fromRange: true,
        id: true,
        idx: true,
        increment: true,
        modifiedBy: true,
        name: true,
        numericValues: true,
        owner: true,
        toRange: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: ItemAttribute })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateItemAttribute(
    @common.Param() params: ItemAttributeWhereUniqueInput,
    @common.Body() data: ItemAttributeUpdateInput
  ): Promise<ItemAttribute | null> {
    try {
      return await this.service.updateItemAttribute({
        where: params,
        data: data,
        select: {
          attributeName: true,
          createdAt: true,
          docstatus: true,
          fromRange: true,
          id: true,
          idx: true,
          increment: true,
          modifiedBy: true,
          name: true,
          numericValues: true,
          owner: true,
          toRange: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: ItemAttribute })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteItemAttribute(
    @common.Param() params: ItemAttributeWhereUniqueInput
  ): Promise<ItemAttribute | null> {
    try {
      return await this.service.deleteItemAttribute({
        where: params,
        select: {
          attributeName: true,
          createdAt: true,
          docstatus: true,
          fromRange: true,
          id: true,
          idx: true,
          increment: true,
          modifiedBy: true,
          name: true,
          numericValues: true,
          owner: true,
          toRange: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
