/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { GrpcMethod } from "@nestjs/microservices";
import { AreaTeleportTriggerService } from "../areaTeleportTrigger.service";
import { AreaTeleportTriggerCreateInput } from "./AreaTeleportTriggerCreateInput";
import { AreaTeleportTriggerWhereInput } from "./AreaTeleportTriggerWhereInput";
import { AreaTeleportTriggerWhereUniqueInput } from "./AreaTeleportTriggerWhereUniqueInput";
import { AreaTeleportTriggerFindManyArgs } from "./AreaTeleportTriggerFindManyArgs";
import { AreaTeleportTriggerUpdateInput } from "./AreaTeleportTriggerUpdateInput";
import { AreaTeleportTrigger } from "./AreaTeleportTrigger";

export class AreaTeleportTriggerGrpcControllerBase {
  constructor(protected readonly service: AreaTeleportTriggerService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: AreaTeleportTrigger })
  @GrpcMethod("AreaTeleportTriggerService", "createAreaTeleportTrigger")
  async createAreaTeleportTrigger(
    @common.Body() data: AreaTeleportTriggerCreateInput
  ): Promise<AreaTeleportTrigger> {
    return await this.service.createAreaTeleportTrigger({
      data: {
        ...data,

        area: {
          connect: data.area,
        },

        portal: {
          connect: data.portal,
        },
      },
      select: {
        area: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        name: true,

        portal: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [AreaTeleportTrigger] })
  @ApiNestedQuery(AreaTeleportTriggerFindManyArgs)
  @GrpcMethod("AreaTeleportTriggerService", "areaTeleportTriggers")
  async areaTeleportTriggers(
    @common.Req() request: Request
  ): Promise<AreaTeleportTrigger[]> {
    const args = plainToClass(AreaTeleportTriggerFindManyArgs, request.query);
    return this.service.areaTeleportTriggers({
      ...args,
      select: {
        area: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        name: true,

        portal: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: AreaTeleportTrigger })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @GrpcMethod("AreaTeleportTriggerService", "areaTeleportTrigger")
  async areaTeleportTrigger(
    @common.Param() params: AreaTeleportTriggerWhereUniqueInput
  ): Promise<AreaTeleportTrigger | null> {
    const result = await this.service.areaTeleportTrigger({
      where: params,
      select: {
        area: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        name: true,

        portal: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: AreaTeleportTrigger })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @GrpcMethod("AreaTeleportTriggerService", "updateAreaTeleportTrigger")
  async updateAreaTeleportTrigger(
    @common.Param() params: AreaTeleportTriggerWhereUniqueInput,
    @common.Body() data: AreaTeleportTriggerUpdateInput
  ): Promise<AreaTeleportTrigger | null> {
    try {
      return await this.service.updateAreaTeleportTrigger({
        where: params,
        data: {
          ...data,

          area: {
            connect: data.area,
          },

          portal: {
            connect: data.portal,
          },
        },
        select: {
          area: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          id: true,
          name: true,

          portal: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: AreaTeleportTrigger })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @GrpcMethod("AreaTeleportTriggerService", "deleteAreaTeleportTrigger")
  async deleteAreaTeleportTrigger(
    @common.Param() params: AreaTeleportTriggerWhereUniqueInput
  ): Promise<AreaTeleportTrigger | null> {
    try {
      return await this.service.deleteAreaTeleportTrigger({
        where: params,
        select: {
          area: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          id: true,
          name: true,

          portal: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
