/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AddressWhereUniqueInput } from "../../address/base/AddressWhereUniqueInput";
import { ValidateNested, IsOptional } from "class-validator";
import { Type } from "class-transformer";
import { CatalogListRelationFilter } from "../../catalog/base/CatalogListRelationFilter";
import { BusinessWhereUniqueInput } from "../../business/base/BusinessWhereUniqueInput";
import { DealListRelationFilter } from "../../deal/base/DealListRelationFilter";
import { StringFilter } from "../../util/StringFilter";
import { OpportunityListRelationFilter } from "../../opportunity/base/OpportunityListRelationFilter";
import { ThreatListRelationFilter } from "../../threat/base/ThreatListRelationFilter";

@InputType()
class UnitWhereInput {
  @ApiProperty({
    required: false,
    type: () => AddressWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => AddressWhereUniqueInput)
  @IsOptional()
  @Field(() => AddressWhereUniqueInput, {
    nullable: true,
  })
  address?: AddressWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: () => CatalogListRelationFilter,
  })
  @ValidateNested()
  @Type(() => CatalogListRelationFilter)
  @IsOptional()
  @Field(() => CatalogListRelationFilter, {
    nullable: true,
  })
  catalogs?: CatalogListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => BusinessWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => BusinessWhereUniqueInput)
  @IsOptional()
  @Field(() => BusinessWhereUniqueInput, {
    nullable: true,
  })
  competitor?: BusinessWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: () => DealListRelationFilter,
  })
  @ValidateNested()
  @Type(() => DealListRelationFilter)
  @IsOptional()
  @Field(() => DealListRelationFilter, {
    nullable: true,
  })
  deals?: DealListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: () => OpportunityListRelationFilter,
  })
  @ValidateNested()
  @Type(() => OpportunityListRelationFilter)
  @IsOptional()
  @Field(() => OpportunityListRelationFilter, {
    nullable: true,
  })
  opportunities?: OpportunityListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => ThreatListRelationFilter,
  })
  @ValidateNested()
  @Type(() => ThreatListRelationFilter)
  @IsOptional()
  @Field(() => ThreatListRelationFilter, {
    nullable: true,
  })
  threats?: ThreatListRelationFilter;
}

export { UnitWhereInput as UnitWhereInput };
