import { SortOrder } from "../../util/SortOrder";

export type StatementOfAccountsOrderByInput = {
  account?: SortOrder;
  ageingBasedOn?: SortOrder;
  basedOnPaymentTerms?: SortOrder;
  body?: SortOrder;
  ccTo?: SortOrder;
  collectionName?: SortOrder;
  company?: SortOrder;
  createdAt?: SortOrder;
  currency?: SortOrder;
  customerCollection?: SortOrder;
  docstatus?: SortOrder;
  enableAutoEmail?: SortOrder;
  filterDuration?: SortOrder;
  financeBook?: SortOrder;
  frequency?: SortOrder;
  fromDate?: SortOrder;
  groupBy?: SortOrder;
  id?: SortOrder;
  idx?: SortOrder;
  ignoreCrDrNotes?: SortOrder;
  ignoreExchangeRateRevaluationJournals?: SortOrder;
  includeAgeing?: SortOrder;
  includeBreak?: SortOrder;
  letterHead?: SortOrder;
  modifiedBy?: SortOrder;
  name?: SortOrder;
  orientation?: SortOrder;
  owner?: SortOrder;
  paymentTermsTemplate?: SortOrder;
  pdfName?: SortOrder;
  postingDate?: SortOrder;
  primaryMandatory?: SortOrder;
  report?: SortOrder;
  salesPartner?: SortOrder;
  salesPerson?: SortOrder;
  sender?: SortOrder;
  showNetValuesInPartyAccount?: SortOrder;
  startDate?: SortOrder;
  subject?: SortOrder;
  termsAndConditions?: SortOrder;
  territory?: SortOrder;
  toDate?: SortOrder;
  updatedAt?: SortOrder;
};
