import { StringNullableFilter } from "../../util/StringNullableFilter";
import { IntNullableFilter } from "../../util/IntNullableFilter";
import { DateTimeNullableFilter } from "../../util/DateTimeNullableFilter";
import { StringFilter } from "../../util/StringFilter";

export type StatementOfAccountsWhereInput = {
  account?: StringNullableFilter;
  ageingBasedOn?: StringNullableFilter;
  basedOnPaymentTerms?: IntNullableFilter;
  body?: StringNullableFilter;
  ccTo?: StringNullableFilter;
  collectionName?: StringNullableFilter;
  company?: StringNullableFilter;
  currency?: StringNullableFilter;
  customerCollection?: StringNullableFilter;
  docstatus?: IntNullableFilter;
  enableAutoEmail?: IntNullableFilter;
  filterDuration?: IntNullableFilter;
  financeBook?: StringNullableFilter;
  frequency?: StringNullableFilter;
  fromDate?: DateTimeNullableFilter;
  groupBy?: StringNullableFilter;
  id?: StringFilter;
  idx?: IntNullableFilter;
  ignoreCrDrNotes?: IntNullableFilter;
  ignoreExchangeRateRevaluationJournals?: IntNullableFilter;
  includeAgeing?: IntNullableFilter;
  includeBreak?: IntNullableFilter;
  letterHead?: StringNullableFilter;
  modifiedBy?: StringNullableFilter;
  name?: StringNullableFilter;
  orientation?: StringNullableFilter;
  owner?: StringNullableFilter;
  paymentTermsTemplate?: StringNullableFilter;
  pdfName?: StringNullableFilter;
  postingDate?: DateTimeNullableFilter;
  primaryMandatory?: IntNullableFilter;
  report?: StringNullableFilter;
  salesPartner?: StringNullableFilter;
  salesPerson?: StringNullableFilter;
  sender?: StringNullableFilter;
  showNetValuesInPartyAccount?: IntNullableFilter;
  startDate?: DateTimeNullableFilter;
  subject?: StringNullableFilter;
  termsAndConditions?: StringNullableFilter;
  territory?: StringNullableFilter;
  toDate?: DateTimeNullableFilter;
};
