import { StringNullableFilter } from "../../util/StringNullableFilter";
import { DateTimeNullableFilter } from "../../util/DateTimeNullableFilter";
import { IntNullableFilter } from "../../util/IntNullableFilter";
import { FloatNullableFilter } from "../../util/FloatNullableFilter";
import { StringFilter } from "../../util/StringFilter";

export type EmployeeWhereInput = {
  attendanceDeviceId?: StringNullableFilter;
  bankAcNo?: StringNullableFilter;
  bankName?: StringNullableFilter;
  bio?: StringNullableFilter;
  bloodGroup?: StringNullableFilter;
  branch?: StringNullableFilter;
  cellNumber?: StringNullableFilter;
  company?: StringNullableFilter;
  companyEmail?: StringNullableFilter;
  contractEndDate?: DateTimeNullableFilter;
  createUserPermission?: IntNullableFilter;
  creation?: DateTimeNullableFilter;
  ctc?: FloatNullableFilter;
  currentAccommodationType?: StringNullableFilter;
  currentAddress?: StringNullableFilter;
  dateOfBirth?: DateTimeNullableFilter;
  dateOfIssue?: DateTimeNullableFilter;
  dateOfJoining?: DateTimeNullableFilter;
  dateOfRetirement?: DateTimeNullableFilter;
  department?: StringNullableFilter;
  designation?: StringNullableFilter;
  docstatus?: IntNullableFilter;
  emergencyPhoneNumber?: StringNullableFilter;
  employee?: StringNullableFilter;
  employeeName?: StringNullableFilter;
  employeeNumber?: StringNullableFilter;
  encashmentDate?: DateTimeNullableFilter;
  familyBackground?: StringNullableFilter;
  feedback?: StringNullableFilter;
  finalConfirmationDate?: DateTimeNullableFilter;
  firstName?: StringNullableFilter;
  gender?: StringNullableFilter;
  healthDetails?: StringNullableFilter;
  heldOn?: DateTimeNullableFilter;
  holidayList?: StringNullableFilter;
  iban?: StringNullableFilter;
  id?: StringFilter;
  idx?: IntNullableFilter;
  image?: StringNullableFilter;
  lastName?: StringNullableFilter;
  leaveEncashed?: StringNullableFilter;
  lft?: IntNullableFilter;
  maritalStatus?: StringNullableFilter;
  middleName?: StringNullableFilter;
  modified?: DateTimeNullableFilter;
  modifiedBy?: StringNullableFilter;
  name?: StringNullableFilter;
  namingSeries?: StringNullableFilter;
  newWorkplace?: StringNullableFilter;
  noticeNumberOfDays?: IntNullableFilter;
  owner?: StringNullableFilter;
  passportNumber?: StringNullableFilter;
  permanentAccommodationType?: StringNullableFilter;
  permanentAddress?: StringNullableFilter;
  personToBeContacted?: StringNullableFilter;
  personalEmail?: StringNullableFilter;
  placeOfIssue?: StringNullableFilter;
  preferedContactEmail?: StringNullableFilter;
  preferedEmail?: StringNullableFilter;
  reasonForLeaving?: StringNullableFilter;
  relation?: StringNullableFilter;
  relievingDate?: DateTimeNullableFilter;
  reportsTo?: StringNullableFilter;
  resignationLetterDate?: DateTimeNullableFilter;
  rgt?: IntNullableFilter;
  salaryCurrency?: StringNullableFilter;
  salaryMode?: StringNullableFilter;
  salutation?: StringNullableFilter;
  scheduledConfirmationDate?: DateTimeNullableFilter;
  status?: StringNullableFilter;
  unsubscribed?: IntNullableFilter;
  userId?: StringNullableFilter;
  validUpto?: DateTimeNullableFilter;
};
