export type BomWebsiteOperation = {
  createdAt: Date;
  creation: Date | null;
  docstatus: number | null;
  id: string;
  idx: number | null;
  modified: Date | null;
  modifiedBy: string | null;
  name: string | null;
  operation: string | null;
  owner: string | null;
  parent: string | null;
  parentfield: string | null;
  parenttype: string | null;
  thumbnail: string | null;
  timeInMins: number | null;
  updatedAt: Date;
  websiteImage: string | null;
  workstation: string | null;
};
