export type PaymentReconciliationLogAllocationUpdateInput = {
  allocatedAmount?: number | null;
  amount?: number | null;
  currency?: string | null;
  differenceAccount?: string | null;
  differenceAmount?: number | null;
  docstatus?: number | null;
  exchangeRate?: number | null;
  idx?: number | null;
  invoiceNumber?: string | null;
  invoiceType?: string | null;
  isAdvance?: string | null;
  modifiedBy?: string | null;
  name?: string | null;
  owner?: string | null;
  parent?: string | null;
  parentfield?: string | null;
  parenttype?: string | null;
  reconciled?: number | null;
  referenceName?: string | null;
  referenceRow?: string | null;
  referenceType?: string | null;
  unreconciledAmount?: number | null;
};
