export type PackedItem = {
  actualBatchQty: number | null;
  actualQty: number | null;
  batchNo: string | null;
  conversionFactor: number | null;
  createdAt: Date;
  creation: Date | null;
  description: string | null;
  docstatus: number | null;
  id: string;
  idx: number | null;
  incomingRate: number | null;
  itemCode: string | null;
  itemName: string | null;
  modified: Date | null;
  modifiedBy: string | null;
  name: string | null;
  orderedQty: number | null;
  owner: string | null;
  packedQty: number | null;
  pageBreak: number | null;
  parent: string | null;
  parentDetailDocname: string | null;
  parentItem: string | null;
  parentfield: string | null;
  parenttype: string | null;
  pickedQty: number | null;
  prevdocDoctype: string | null;
  projectedQty: number | null;
  qty: number | null;
  rate: number | null;
  serialAndBatchBundle: string | null;
  serialNo: string | null;
  targetWarehouse: string | null;
  uom: string | null;
  updatedAt: Date;
  useSerialBatchFields: number | null;
  warehouse: string | null;
};
