import { FloatNullableFilter } from "../../util/FloatNullableFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { DateTimeNullableFilter } from "../../util/DateTimeNullableFilter";
import { IntNullableFilter } from "../../util/IntNullableFilter";
import { StringFilter } from "../../util/StringFilter";

export type PackedItemWhereInput = {
  actualBatchQty?: FloatNullableFilter;
  actualQty?: FloatNullableFilter;
  batchNo?: StringNullableFilter;
  conversionFactor?: FloatNullableFilter;
  creation?: DateTimeNullableFilter;
  description?: StringNullableFilter;
  docstatus?: IntNullableFilter;
  id?: StringFilter;
  idx?: IntNullableFilter;
  incomingRate?: FloatNullableFilter;
  itemCode?: StringNullableFilter;
  itemName?: StringNullableFilter;
  modified?: DateTimeNullableFilter;
  modifiedBy?: StringNullableFilter;
  name?: StringNullableFilter;
  orderedQty?: FloatNullableFilter;
  owner?: StringNullableFilter;
  packedQty?: FloatNullableFilter;
  pageBreak?: IntNullableFilter;
  parent?: StringNullableFilter;
  parentDetailDocname?: StringNullableFilter;
  parentItem?: StringNullableFilter;
  parentfield?: StringNullableFilter;
  parenttype?: StringNullableFilter;
  pickedQty?: FloatNullableFilter;
  prevdocDoctype?: StringNullableFilter;
  projectedQty?: FloatNullableFilter;
  qty?: FloatNullableFilter;
  rate?: FloatNullableFilter;
  serialAndBatchBundle?: StringNullableFilter;
  serialNo?: StringNullableFilter;
  targetWarehouse?: StringNullableFilter;
  uom?: StringNullableFilter;
  useSerialBatchFields?: IntNullableFilter;
  warehouse?: StringNullableFilter;
};
