import { SortOrder } from "../../util/SortOrder";

export type PackedItemOrderByInput = {
  actualBatchQty?: SortOrder;
  actualQty?: SortOrder;
  batchNo?: SortOrder;
  conversionFactor?: SortOrder;
  createdAt?: SortOrder;
  creation?: SortOrder;
  description?: SortOrder;
  docstatus?: SortOrder;
  id?: SortOrder;
  idx?: SortOrder;
  incomingRate?: SortOrder;
  itemCode?: SortOrder;
  itemName?: SortOrder;
  modified?: SortOrder;
  modifiedBy?: SortOrder;
  name?: SortOrder;
  orderedQty?: SortOrder;
  owner?: SortOrder;
  packedQty?: SortOrder;
  pageBreak?: SortOrder;
  parent?: SortOrder;
  parentDetailDocname?: SortOrder;
  parentItem?: SortOrder;
  parentfield?: SortOrder;
  parenttype?: SortOrder;
  pickedQty?: SortOrder;
  prevdocDoctype?: SortOrder;
  projectedQty?: SortOrder;
  qty?: SortOrder;
  rate?: SortOrder;
  serialAndBatchBundle?: SortOrder;
  serialNo?: SortOrder;
  targetWarehouse?: SortOrder;
  uom?: SortOrder;
  updatedAt?: SortOrder;
  useSerialBatchFields?: SortOrder;
  warehouse?: SortOrder;
};
