export type BisectNodes = {
  balanceSheetSummary: number | null;
  createdAt: Date;
  creation: Date | null;
  difference: number | null;
  docstatus: number | null;
  generated: number | null;
  id: string;
  idx: number | null;
  leftChild: string | null;
  modified: Date | null;
  modifiedBy: string | null;
  name: number | null;
  owner: string | null;
  periodFromDate: Date | null;
  periodToDate: Date | null;
  profitLossSummary: number | null;
  rightChild: string | null;
  root: string | null;
  updatedAt: Date;
};
