export type AdvanceTaxesAndChargesUpdateInput = {
  accountHead?: string | null;
  addDeductTax?: string | null;
  allocatedAmount?: number | null;
  baseTaxAmount?: number | null;
  baseTotal?: number | null;
  chargeType?: string | null;
  costCenter?: string | null;
  currency?: string | null;
  description?: string | null;
  docstatus?: number | null;
  idx?: number | null;
  includedInPaidAmount?: number | null;
  name?: string | null;
  owner?: string | null;
  parent?: string | null;
  parentfield?: string | null;
  parenttype?: string | null;
  rate?: number | null;
  rowId?: string | null;
  taxAmount?: number | null;
  total?: number | null;
};
