import { StringNullableFilter } from "../../util/StringNullableFilter";
import { DateTimeNullableFilter } from "../../util/DateTimeNullableFilter";
import { StringFilter } from "../../util/StringFilter";
import { IntNullableFilter } from "../../util/IntNullableFilter";
import { FloatNullableFilter } from "../../util/FloatNullableFilter";

export type ClreDedVlutPdlWhereInput = {
  delYn?: StringNullableFilter;
  frstRegstId?: StringNullableFilter;
  frstRgsrDttm?: DateTimeNullableFilter;
  id?: StringFilter;
  lastChgDttm?: DateTimeNullableFilter;
  lastChprId?: StringNullableFilter;
  mdfyDgcnt?: IntNullableFilter;
  pdlsCachAmt?: FloatNullableFilter;
  pdlsCachCurrCd?: StringNullableFilter;
  pdlsCachFxrt?: FloatNullableFilter;
  pdlsCachNcyAmt?: FloatNullableFilter;
  pdlsDdctAmt?: FloatNullableFilter;
  pdlsDdctCurrCd?: StringNullableFilter;
  pdlsDdctFxrt?: FloatNullableFilter;
  pdlsDdctNcyAmt?: FloatNullableFilter;
  pdlsInfeeAmt?: FloatNullableFilter;
  pdlsInfeeCurrCd?: StringNullableFilter;
  pdlsInfeeFxrt?: FloatNullableFilter;
  pdlsInfeeNcyAmt?: FloatNullableFilter;
  pdlsInvcAmt?: FloatNullableFilter;
  pdlsInvcCurrCd?: StringNullableFilter;
  pdlsInvcFxrt?: FloatNullableFilter;
  pdlsInvcNcyAmt?: FloatNullableFilter;
  pdlsInvcUsdAmt?: FloatNullableFilter;
  pdlsMprcBaseVal?: FloatNullableFilter;
  pdlsMprcCurrCd?: StringNullableFilter;
  pdlsMprcNcyAmt?: FloatNullableFilter;
  pdlsMprcTpCd?: StringNullableFilter;
  pdlsMprcUsdAmt?: FloatNullableFilter;
  pdlsMprcUtAmt?: FloatNullableFilter;
  pdlsNo?: StringNullableFilter;
  pdlsOtcstAmt?: FloatNullableFilter;
  pdlsOtcstCurrCd?: StringNullableFilter;
  pdlsOtcstFxrt?: FloatNullableFilter;
  pdlsOtcstNcyAmt?: FloatNullableFilter;
  pdlsTxbsNcyAmt?: FloatNullableFilter;
  pdlsTxbsUsdAmt?: FloatNullableFilter;
  pdlsVlutNcyAmt?: FloatNullableFilter;
  pdlsVlutUsdAmt?: FloatNullableFilter;
  reffNo?: StringNullableFilter;
};
