export type ClreDedVlutPdl = {
  createdAt: Date;
  delYn: string | null;
  frstRegstId: string | null;
  frstRgsrDttm: Date | null;
  id: string;
  lastChgDttm: Date | null;
  lastChprId: string | null;
  mdfyDgcnt: number | null;
  pdlsCachAmt: number | null;
  pdlsCachCurrCd: string | null;
  pdlsCachFxrt: number | null;
  pdlsCachNcyAmt: number | null;
  pdlsDdctAmt: number | null;
  pdlsDdctCurrCd: string | null;
  pdlsDdctFxrt: number | null;
  pdlsDdctNcyAmt: number | null;
  pdlsInfeeAmt: number | null;
  pdlsInfeeCurrCd: string | null;
  pdlsInfeeFxrt: number | null;
  pdlsInfeeNcyAmt: number | null;
  pdlsInvcAmt: number | null;
  pdlsInvcCurrCd: string | null;
  pdlsInvcFxrt: number | null;
  pdlsInvcNcyAmt: number | null;
  pdlsInvcUsdAmt: number | null;
  pdlsMprcBaseVal: number | null;
  pdlsMprcCurrCd: string | null;
  pdlsMprcNcyAmt: number | null;
  pdlsMprcTpCd: string | null;
  pdlsMprcUsdAmt: number | null;
  pdlsMprcUtAmt: number | null;
  pdlsNo: string | null;
  pdlsOtcstAmt: number | null;
  pdlsOtcstCurrCd: string | null;
  pdlsOtcstFxrt: number | null;
  pdlsOtcstNcyAmt: number | null;
  pdlsTxbsNcyAmt: number | null;
  pdlsTxbsUsdAmt: number | null;
  pdlsVlutNcyAmt: number | null;
  pdlsVlutUsdAmt: number | null;
  reffNo: string | null;
  updatedAt: Date;
};
