import { SortOrder } from "../../util/SortOrder";

export type ClreDedVlutPdlOrderByInput = {
  createdAt?: SortOrder;
  delYn?: SortOrder;
  frstRegstId?: SortOrder;
  frstRgsrDttm?: SortOrder;
  id?: SortOrder;
  lastChgDttm?: SortOrder;
  lastChprId?: SortOrder;
  mdfyDgcnt?: SortOrder;
  pdlsCachAmt?: SortOrder;
  pdlsCachCurrCd?: SortOrder;
  pdlsCachFxrt?: SortOrder;
  pdlsCachNcyAmt?: SortOrder;
  pdlsDdctAmt?: SortOrder;
  pdlsDdctCurrCd?: SortOrder;
  pdlsDdctFxrt?: SortOrder;
  pdlsDdctNcyAmt?: SortOrder;
  pdlsInfeeAmt?: SortOrder;
  pdlsInfeeCurrCd?: SortOrder;
  pdlsInfeeFxrt?: SortOrder;
  pdlsInfeeNcyAmt?: SortOrder;
  pdlsInvcAmt?: SortOrder;
  pdlsInvcCurrCd?: SortOrder;
  pdlsInvcFxrt?: SortOrder;
  pdlsInvcNcyAmt?: SortOrder;
  pdlsInvcUsdAmt?: SortOrder;
  pdlsMprcBaseVal?: SortOrder;
  pdlsMprcCurrCd?: SortOrder;
  pdlsMprcNcyAmt?: SortOrder;
  pdlsMprcTpCd?: SortOrder;
  pdlsMprcUsdAmt?: SortOrder;
  pdlsMprcUtAmt?: SortOrder;
  pdlsNo?: SortOrder;
  pdlsOtcstAmt?: SortOrder;
  pdlsOtcstCurrCd?: SortOrder;
  pdlsOtcstFxrt?: SortOrder;
  pdlsOtcstNcyAmt?: SortOrder;
  pdlsTxbsNcyAmt?: SortOrder;
  pdlsTxbsUsdAmt?: SortOrder;
  pdlsVlutNcyAmt?: SortOrder;
  pdlsVlutUsdAmt?: SortOrder;
  reffNo?: SortOrder;
  updatedAt?: SortOrder;
};
