export type ConnectedApp = {
  authorizationUri: string | null;
  clientId: string | null;
  clientSecret: string | null;
  createdAt: Date;
  creation: Date | null;
  docstatus: number | null;
  id: string;
  idx: number | null;
  introspectionUri: string | null;
  modified: Date | null;
  modifiedBy: string | null;
  name: string | null;
  openidConfiguration: string | null;
  owner: string | null;
  providerName: string | null;
  redirectUri: string | null;
  revocationUri: string | null;
  tokenUri: string | null;
  updatedAt: Date;
  userinfoUri: string | null;
};
