export type PackingSlipItem = {
  batchNo: string | null;
  createdAt: Date;
  creation: Date | null;
  description: string | null;
  dnDetail: string | null;
  docstatus: number | null;
  id: string;
  idx: number | null;
  itemCode: string | null;
  itemName: string | null;
  modified: Date | null;
  modifiedBy: string | null;
  name: string | null;
  netWeight: number | null;
  owner: string | null;
  pageBreak: number | null;
  parent: string | null;
  parentfield: string | null;
  parenttype: string | null;
  piDetail: string | null;
  qty: number | null;
  stockUom: string | null;
  updatedAt: Date;
  weightUom: string | null;
};
