import { Test } from "@nestjs/testing";
import {
  INestApplication,
  HttpStatus,
  ExecutionContext,
  CallHandler,
} from "@nestjs/common";
import request from "supertest";
import { ACGuard } from "nest-access-control";
import { DefaultAuthGuard } from "../../auth/defaultAuth.guard";
import { ACLModule } from "../../auth/acl.module";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { map } from "rxjs";
import { PurchaseInvoiceController } from "../purchaseInvoice.controller";
import { PurchaseInvoiceService } from "../purchaseInvoice.service";

const nonExistingId = "nonExistingId";
const existingId = "existingId";
const CREATE_INPUT = {
  additionalDiscountPercentage: 42.42,
  addressDisplay: "exampleAddressDisplay",
  againstExpenseAccount: "exampleAgainstExpenseAccount",
  allocateAdvancesAutomatically: 42,
  amendedFrom: "exampleAmendedFrom",
  applyDiscountOn: "exampleApplyDiscountOn",
  applyTds: 42,
  autoRepeat: "exampleAutoRepeat",
  baseDiscountAmount: 42.42,
  baseGrandTotal: 42.42,
  baseInWords: "exampleBaseInWords",
  baseNetTotal: 42.42,
  basePaidAmount: 42.42,
  baseRoundedTotal: 42.42,
  baseRoundingAdjustment: 42.42,
  baseTaxWithholdingNetTotal: 42.42,
  baseTaxesAndChargesAdded: 42.42,
  baseTaxesAndChargesDeducted: 42.42,
  baseTotal: 42.42,
  baseTotalTaxesAndCharges: 42.42,
  baseWriteOffAmount: 42.42,
  billDate: new Date(),
  billNo: "exampleBillNo",
  billingAddress: "exampleBillingAddress",
  billingAddressDisplay: "exampleBillingAddressDisplay",
  buyingPriceList: "exampleBuyingPriceList",
  cashBankAccount: "exampleCashBankAccount",
  clearanceDate: new Date(),
  company: "exampleCompany",
  contactDisplay: "exampleContactDisplay",
  contactEmail: "exampleContactEmail",
  contactMobile: "exampleContactMobile",
  contactPerson: "exampleContactPerson",
  conversionRate: 42.42,
  costCenter: "exampleCostCenter",
  createdAt: new Date(),
  creation: new Date(),
  creditTo: "exampleCreditTo",
  currency: "exampleCurrency",
  disableRoundedTotal: 42,
  discountAmount: 42.42,
  docstatus: 42,
  dueDate: new Date(),
  fromDate: new Date(),
  grandTotal: 42.42,
  groupSameItems: 42,
  holdComment: "exampleHoldComment",
  id: "exampleId",
  idx: 42,
  ignoreDefaultPaymentTermsTemplate: 42,
  ignorePricingRule: 42,
  inWords: "exampleInWords",
  incoterm: "exampleIncoterm",
  interCompanyInvoiceReference: "exampleInterCompanyInvoiceReference",
  isInternalSupplier: 42,
  isOldSubcontractingFlow: 42,
  isOpening: "exampleIsOpening",
  isPaid: 42,
  isReturn: 42,
  isSubcontracted: 42,
  language: "exampleLanguage",
  letterHead: "exampleLetterHead",
  modeOfPayment: "exampleModeOfPayment",
  modified: new Date(),
  modifiedBy: "exampleModifiedBy",
  name: "exampleName",
  namedPlace: "exampleNamedPlace",
  namingSeries: "exampleNamingSeries",
  netTotal: 42.42,
  onHold: 42,
  onlyIncludeAllocatedPayments: 42,
  otherChargesCalculation: "exampleOtherChargesCalculation",
  outstandingAmount: 42.42,
  owner: "exampleOwner",
  paidAmount: 42.42,
  partyAccountCurrency: "examplePartyAccountCurrency",
  paymentTermsTemplate: "examplePaymentTermsTemplate",
  perReceived: 42.42,
  plcConversionRate: 42.42,
  postingDate: new Date(),
  postingTime: "examplePostingTime",
  priceListCurrency: "examplePriceListCurrency",
  project: "exampleProject",
  rejectedWarehouse: "exampleRejectedWarehouse",
  releaseDate: new Date(),
  remarks: "exampleRemarks",
  representsCompany: "exampleRepresentsCompany",
  returnAgainst: "exampleReturnAgainst",
  roundedTotal: 42.42,
  roundingAdjustment: 42.42,
  scanBarcode: "exampleScanBarcode",
  selectPrintHeading: "exampleSelectPrintHeading",
  setFromWarehouse: "exampleSetFromWarehouse",
  setPostingTime: 42,
  setWarehouse: "exampleSetWarehouse",
  shippingAddress: "exampleShippingAddress",
  shippingAddressDisplay: "exampleShippingAddressDisplay",
  shippingRule: "exampleShippingRule",
  status: "exampleStatus",
  subscription: "exampleSubscription",
  supplier: "exampleSupplier",
  supplierAddress: "exampleSupplierAddress",
  supplierGroup: "exampleSupplierGroup",
  supplierName: "exampleSupplierName",
  supplierWarehouse: "exampleSupplierWarehouse",
  taxCategory: "exampleTaxCategory",
  taxId: "exampleTaxId",
  taxWithholdingCategory: "exampleTaxWithholdingCategory",
  taxWithholdingNetTotal: 42.42,
  taxesAndCharges: "exampleTaxesAndCharges",
  taxesAndChargesAdded: 42.42,
  taxesAndChargesDeducted: 42.42,
  tcName: "exampleTcName",
  terms: "exampleTerms",
  title: "exampleTitle",
  toDate: new Date(),
  total: 42.42,
  totalAdvance: 42.42,
  totalNetWeight: 42.42,
  totalQty: 42.42,
  totalTaxesAndCharges: 42.42,
  unrealizedProfitLossAccount: "exampleUnrealizedProfitLossAccount",
  updateBilledAmountInPurchaseOrder: 42,
  updateBilledAmountInPurchaseReceipt: 42,
  updateOutstandingForSelf: 42,
  updateStock: 42,
  updatedAt: new Date(),
  useCompanyRoundoffCostCenter: 42,
  useTransactionDateExchangeRate: 42,
  writeOffAccount: "exampleWriteOffAccount",
  writeOffAmount: 42.42,
  writeOffCostCenter: "exampleWriteOffCostCenter",
};
const CREATE_RESULT = {
  additionalDiscountPercentage: 42.42,
  addressDisplay: "exampleAddressDisplay",
  againstExpenseAccount: "exampleAgainstExpenseAccount",
  allocateAdvancesAutomatically: 42,
  amendedFrom: "exampleAmendedFrom",
  applyDiscountOn: "exampleApplyDiscountOn",
  applyTds: 42,
  autoRepeat: "exampleAutoRepeat",
  baseDiscountAmount: 42.42,
  baseGrandTotal: 42.42,
  baseInWords: "exampleBaseInWords",
  baseNetTotal: 42.42,
  basePaidAmount: 42.42,
  baseRoundedTotal: 42.42,
  baseRoundingAdjustment: 42.42,
  baseTaxWithholdingNetTotal: 42.42,
  baseTaxesAndChargesAdded: 42.42,
  baseTaxesAndChargesDeducted: 42.42,
  baseTotal: 42.42,
  baseTotalTaxesAndCharges: 42.42,
  baseWriteOffAmount: 42.42,
  billDate: new Date(),
  billNo: "exampleBillNo",
  billingAddress: "exampleBillingAddress",
  billingAddressDisplay: "exampleBillingAddressDisplay",
  buyingPriceList: "exampleBuyingPriceList",
  cashBankAccount: "exampleCashBankAccount",
  clearanceDate: new Date(),
  company: "exampleCompany",
  contactDisplay: "exampleContactDisplay",
  contactEmail: "exampleContactEmail",
  contactMobile: "exampleContactMobile",
  contactPerson: "exampleContactPerson",
  conversionRate: 42.42,
  costCenter: "exampleCostCenter",
  createdAt: new Date(),
  creation: new Date(),
  creditTo: "exampleCreditTo",
  currency: "exampleCurrency",
  disableRoundedTotal: 42,
  discountAmount: 42.42,
  docstatus: 42,
  dueDate: new Date(),
  fromDate: new Date(),
  grandTotal: 42.42,
  groupSameItems: 42,
  holdComment: "exampleHoldComment",
  id: "exampleId",
  idx: 42,
  ignoreDefaultPaymentTermsTemplate: 42,
  ignorePricingRule: 42,
  inWords: "exampleInWords",
  incoterm: "exampleIncoterm",
  interCompanyInvoiceReference: "exampleInterCompanyInvoiceReference",
  isInternalSupplier: 42,
  isOldSubcontractingFlow: 42,
  isOpening: "exampleIsOpening",
  isPaid: 42,
  isReturn: 42,
  isSubcontracted: 42,
  language: "exampleLanguage",
  letterHead: "exampleLetterHead",
  modeOfPayment: "exampleModeOfPayment",
  modified: new Date(),
  modifiedBy: "exampleModifiedBy",
  name: "exampleName",
  namedPlace: "exampleNamedPlace",
  namingSeries: "exampleNamingSeries",
  netTotal: 42.42,
  onHold: 42,
  onlyIncludeAllocatedPayments: 42,
  otherChargesCalculation: "exampleOtherChargesCalculation",
  outstandingAmount: 42.42,
  owner: "exampleOwner",
  paidAmount: 42.42,
  partyAccountCurrency: "examplePartyAccountCurrency",
  paymentTermsTemplate: "examplePaymentTermsTemplate",
  perReceived: 42.42,
  plcConversionRate: 42.42,
  postingDate: new Date(),
  postingTime: "examplePostingTime",
  priceListCurrency: "examplePriceListCurrency",
  project: "exampleProject",
  rejectedWarehouse: "exampleRejectedWarehouse",
  releaseDate: new Date(),
  remarks: "exampleRemarks",
  representsCompany: "exampleRepresentsCompany",
  returnAgainst: "exampleReturnAgainst",
  roundedTotal: 42.42,
  roundingAdjustment: 42.42,
  scanBarcode: "exampleScanBarcode",
  selectPrintHeading: "exampleSelectPrintHeading",
  setFromWarehouse: "exampleSetFromWarehouse",
  setPostingTime: 42,
  setWarehouse: "exampleSetWarehouse",
  shippingAddress: "exampleShippingAddress",
  shippingAddressDisplay: "exampleShippingAddressDisplay",
  shippingRule: "exampleShippingRule",
  status: "exampleStatus",
  subscription: "exampleSubscription",
  supplier: "exampleSupplier",
  supplierAddress: "exampleSupplierAddress",
  supplierGroup: "exampleSupplierGroup",
  supplierName: "exampleSupplierName",
  supplierWarehouse: "exampleSupplierWarehouse",
  taxCategory: "exampleTaxCategory",
  taxId: "exampleTaxId",
  taxWithholdingCategory: "exampleTaxWithholdingCategory",
  taxWithholdingNetTotal: 42.42,
  taxesAndCharges: "exampleTaxesAndCharges",
  taxesAndChargesAdded: 42.42,
  taxesAndChargesDeducted: 42.42,
  tcName: "exampleTcName",
  terms: "exampleTerms",
  title: "exampleTitle",
  toDate: new Date(),
  total: 42.42,
  totalAdvance: 42.42,
  totalNetWeight: 42.42,
  totalQty: 42.42,
  totalTaxesAndCharges: 42.42,
  unrealizedProfitLossAccount: "exampleUnrealizedProfitLossAccount",
  updateBilledAmountInPurchaseOrder: 42,
  updateBilledAmountInPurchaseReceipt: 42,
  updateOutstandingForSelf: 42,
  updateStock: 42,
  updatedAt: new Date(),
  useCompanyRoundoffCostCenter: 42,
  useTransactionDateExchangeRate: 42,
  writeOffAccount: "exampleWriteOffAccount",
  writeOffAmount: 42.42,
  writeOffCostCenter: "exampleWriteOffCostCenter",
};
const FIND_MANY_RESULT = [
  {
    additionalDiscountPercentage: 42.42,
    addressDisplay: "exampleAddressDisplay",
    againstExpenseAccount: "exampleAgainstExpenseAccount",
    allocateAdvancesAutomatically: 42,
    amendedFrom: "exampleAmendedFrom",
    applyDiscountOn: "exampleApplyDiscountOn",
    applyTds: 42,
    autoRepeat: "exampleAutoRepeat",
    baseDiscountAmount: 42.42,
    baseGrandTotal: 42.42,
    baseInWords: "exampleBaseInWords",
    baseNetTotal: 42.42,
    basePaidAmount: 42.42,
    baseRoundedTotal: 42.42,
    baseRoundingAdjustment: 42.42,
    baseTaxWithholdingNetTotal: 42.42,
    baseTaxesAndChargesAdded: 42.42,
    baseTaxesAndChargesDeducted: 42.42,
    baseTotal: 42.42,
    baseTotalTaxesAndCharges: 42.42,
    baseWriteOffAmount: 42.42,
    billDate: new Date(),
    billNo: "exampleBillNo",
    billingAddress: "exampleBillingAddress",
    billingAddressDisplay: "exampleBillingAddressDisplay",
    buyingPriceList: "exampleBuyingPriceList",
    cashBankAccount: "exampleCashBankAccount",
    clearanceDate: new Date(),
    company: "exampleCompany",
    contactDisplay: "exampleContactDisplay",
    contactEmail: "exampleContactEmail",
    contactMobile: "exampleContactMobile",
    contactPerson: "exampleContactPerson",
    conversionRate: 42.42,
    costCenter: "exampleCostCenter",
    createdAt: new Date(),
    creation: new Date(),
    creditTo: "exampleCreditTo",
    currency: "exampleCurrency",
    disableRoundedTotal: 42,
    discountAmount: 42.42,
    docstatus: 42,
    dueDate: new Date(),
    fromDate: new Date(),
    grandTotal: 42.42,
    groupSameItems: 42,
    holdComment: "exampleHoldComment",
    id: "exampleId",
    idx: 42,
    ignoreDefaultPaymentTermsTemplate: 42,
    ignorePricingRule: 42,
    inWords: "exampleInWords",
    incoterm: "exampleIncoterm",
    interCompanyInvoiceReference: "exampleInterCompanyInvoiceReference",
    isInternalSupplier: 42,
    isOldSubcontractingFlow: 42,
    isOpening: "exampleIsOpening",
    isPaid: 42,
    isReturn: 42,
    isSubcontracted: 42,
    language: "exampleLanguage",
    letterHead: "exampleLetterHead",
    modeOfPayment: "exampleModeOfPayment",
    modified: new Date(),
    modifiedBy: "exampleModifiedBy",
    name: "exampleName",
    namedPlace: "exampleNamedPlace",
    namingSeries: "exampleNamingSeries",
    netTotal: 42.42,
    onHold: 42,
    onlyIncludeAllocatedPayments: 42,
    otherChargesCalculation: "exampleOtherChargesCalculation",
    outstandingAmount: 42.42,
    owner: "exampleOwner",
    paidAmount: 42.42,
    partyAccountCurrency: "examplePartyAccountCurrency",
    paymentTermsTemplate: "examplePaymentTermsTemplate",
    perReceived: 42.42,
    plcConversionRate: 42.42,
    postingDate: new Date(),
    postingTime: "examplePostingTime",
    priceListCurrency: "examplePriceListCurrency",
    project: "exampleProject",
    rejectedWarehouse: "exampleRejectedWarehouse",
    releaseDate: new Date(),
    remarks: "exampleRemarks",
    representsCompany: "exampleRepresentsCompany",
    returnAgainst: "exampleReturnAgainst",
    roundedTotal: 42.42,
    roundingAdjustment: 42.42,
    scanBarcode: "exampleScanBarcode",
    selectPrintHeading: "exampleSelectPrintHeading",
    setFromWarehouse: "exampleSetFromWarehouse",
    setPostingTime: 42,
    setWarehouse: "exampleSetWarehouse",
    shippingAddress: "exampleShippingAddress",
    shippingAddressDisplay: "exampleShippingAddressDisplay",
    shippingRule: "exampleShippingRule",
    status: "exampleStatus",
    subscription: "exampleSubscription",
    supplier: "exampleSupplier",
    supplierAddress: "exampleSupplierAddress",
    supplierGroup: "exampleSupplierGroup",
    supplierName: "exampleSupplierName",
    supplierWarehouse: "exampleSupplierWarehouse",
    taxCategory: "exampleTaxCategory",
    taxId: "exampleTaxId",
    taxWithholdingCategory: "exampleTaxWithholdingCategory",
    taxWithholdingNetTotal: 42.42,
    taxesAndCharges: "exampleTaxesAndCharges",
    taxesAndChargesAdded: 42.42,
    taxesAndChargesDeducted: 42.42,
    tcName: "exampleTcName",
    terms: "exampleTerms",
    title: "exampleTitle",
    toDate: new Date(),
    total: 42.42,
    totalAdvance: 42.42,
    totalNetWeight: 42.42,
    totalQty: 42.42,
    totalTaxesAndCharges: 42.42,
    unrealizedProfitLossAccount: "exampleUnrealizedProfitLossAccount",
    updateBilledAmountInPurchaseOrder: 42,
    updateBilledAmountInPurchaseReceipt: 42,
    updateOutstandingForSelf: 42,
    updateStock: 42,
    updatedAt: new Date(),
    useCompanyRoundoffCostCenter: 42,
    useTransactionDateExchangeRate: 42,
    writeOffAccount: "exampleWriteOffAccount",
    writeOffAmount: 42.42,
    writeOffCostCenter: "exampleWriteOffCostCenter",
  },
];
const FIND_ONE_RESULT = {
  additionalDiscountPercentage: 42.42,
  addressDisplay: "exampleAddressDisplay",
  againstExpenseAccount: "exampleAgainstExpenseAccount",
  allocateAdvancesAutomatically: 42,
  amendedFrom: "exampleAmendedFrom",
  applyDiscountOn: "exampleApplyDiscountOn",
  applyTds: 42,
  autoRepeat: "exampleAutoRepeat",
  baseDiscountAmount: 42.42,
  baseGrandTotal: 42.42,
  baseInWords: "exampleBaseInWords",
  baseNetTotal: 42.42,
  basePaidAmount: 42.42,
  baseRoundedTotal: 42.42,
  baseRoundingAdjustment: 42.42,
  baseTaxWithholdingNetTotal: 42.42,
  baseTaxesAndChargesAdded: 42.42,
  baseTaxesAndChargesDeducted: 42.42,
  baseTotal: 42.42,
  baseTotalTaxesAndCharges: 42.42,
  baseWriteOffAmount: 42.42,
  billDate: new Date(),
  billNo: "exampleBillNo",
  billingAddress: "exampleBillingAddress",
  billingAddressDisplay: "exampleBillingAddressDisplay",
  buyingPriceList: "exampleBuyingPriceList",
  cashBankAccount: "exampleCashBankAccount",
  clearanceDate: new Date(),
  company: "exampleCompany",
  contactDisplay: "exampleContactDisplay",
  contactEmail: "exampleContactEmail",
  contactMobile: "exampleContactMobile",
  contactPerson: "exampleContactPerson",
  conversionRate: 42.42,
  costCenter: "exampleCostCenter",
  createdAt: new Date(),
  creation: new Date(),
  creditTo: "exampleCreditTo",
  currency: "exampleCurrency",
  disableRoundedTotal: 42,
  discountAmount: 42.42,
  docstatus: 42,
  dueDate: new Date(),
  fromDate: new Date(),
  grandTotal: 42.42,
  groupSameItems: 42,
  holdComment: "exampleHoldComment",
  id: "exampleId",
  idx: 42,
  ignoreDefaultPaymentTermsTemplate: 42,
  ignorePricingRule: 42,
  inWords: "exampleInWords",
  incoterm: "exampleIncoterm",
  interCompanyInvoiceReference: "exampleInterCompanyInvoiceReference",
  isInternalSupplier: 42,
  isOldSubcontractingFlow: 42,
  isOpening: "exampleIsOpening",
  isPaid: 42,
  isReturn: 42,
  isSubcontracted: 42,
  language: "exampleLanguage",
  letterHead: "exampleLetterHead",
  modeOfPayment: "exampleModeOfPayment",
  modified: new Date(),
  modifiedBy: "exampleModifiedBy",
  name: "exampleName",
  namedPlace: "exampleNamedPlace",
  namingSeries: "exampleNamingSeries",
  netTotal: 42.42,
  onHold: 42,
  onlyIncludeAllocatedPayments: 42,
  otherChargesCalculation: "exampleOtherChargesCalculation",
  outstandingAmount: 42.42,
  owner: "exampleOwner",
  paidAmount: 42.42,
  partyAccountCurrency: "examplePartyAccountCurrency",
  paymentTermsTemplate: "examplePaymentTermsTemplate",
  perReceived: 42.42,
  plcConversionRate: 42.42,
  postingDate: new Date(),
  postingTime: "examplePostingTime",
  priceListCurrency: "examplePriceListCurrency",
  project: "exampleProject",
  rejectedWarehouse: "exampleRejectedWarehouse",
  releaseDate: new Date(),
  remarks: "exampleRemarks",
  representsCompany: "exampleRepresentsCompany",
  returnAgainst: "exampleReturnAgainst",
  roundedTotal: 42.42,
  roundingAdjustment: 42.42,
  scanBarcode: "exampleScanBarcode",
  selectPrintHeading: "exampleSelectPrintHeading",
  setFromWarehouse: "exampleSetFromWarehouse",
  setPostingTime: 42,
  setWarehouse: "exampleSetWarehouse",
  shippingAddress: "exampleShippingAddress",
  shippingAddressDisplay: "exampleShippingAddressDisplay",
  shippingRule: "exampleShippingRule",
  status: "exampleStatus",
  subscription: "exampleSubscription",
  supplier: "exampleSupplier",
  supplierAddress: "exampleSupplierAddress",
  supplierGroup: "exampleSupplierGroup",
  supplierName: "exampleSupplierName",
  supplierWarehouse: "exampleSupplierWarehouse",
  taxCategory: "exampleTaxCategory",
  taxId: "exampleTaxId",
  taxWithholdingCategory: "exampleTaxWithholdingCategory",
  taxWithholdingNetTotal: 42.42,
  taxesAndCharges: "exampleTaxesAndCharges",
  taxesAndChargesAdded: 42.42,
  taxesAndChargesDeducted: 42.42,
  tcName: "exampleTcName",
  terms: "exampleTerms",
  title: "exampleTitle",
  toDate: new Date(),
  total: 42.42,
  totalAdvance: 42.42,
  totalNetWeight: 42.42,
  totalQty: 42.42,
  totalTaxesAndCharges: 42.42,
  unrealizedProfitLossAccount: "exampleUnrealizedProfitLossAccount",
  updateBilledAmountInPurchaseOrder: 42,
  updateBilledAmountInPurchaseReceipt: 42,
  updateOutstandingForSelf: 42,
  updateStock: 42,
  updatedAt: new Date(),
  useCompanyRoundoffCostCenter: 42,
  useTransactionDateExchangeRate: 42,
  writeOffAccount: "exampleWriteOffAccount",
  writeOffAmount: 42.42,
  writeOffCostCenter: "exampleWriteOffCostCenter",
};

const service = {
  createPurchaseInvoice() {
    return CREATE_RESULT;
  },
  purchaseInvoices: () => FIND_MANY_RESULT,
  purchaseInvoice: ({ where }: { where: { id: string } }) => {
    switch (where.id) {
      case existingId:
        return FIND_ONE_RESULT;
      case nonExistingId:
        return null;
    }
  },
};

const basicAuthGuard = {
  canActivate: (context: ExecutionContext) => {
    const argumentHost = context.switchToHttp();
    const request = argumentHost.getRequest();
    request.user = {
      roles: ["user"],
    };
    return true;
  },
};

const acGuard = {
  canActivate: () => {
    return true;
  },
};

const aclFilterResponseInterceptor = {
  intercept: (context: ExecutionContext, next: CallHandler) => {
    return next.handle().pipe(
      map((data) => {
        return data;
      })
    );
  },
};
const aclValidateRequestInterceptor = {
  intercept: (context: ExecutionContext, next: CallHandler) => {
    return next.handle();
  },
};

describe("PurchaseInvoice", () => {
  let app: INestApplication;

  beforeAll(async () => {
    const moduleRef = await Test.createTestingModule({
      providers: [
        {
          provide: PurchaseInvoiceService,
          useValue: service,
        },
      ],
      controllers: [PurchaseInvoiceController],
      imports: [ACLModule],
    })
      .overrideGuard(DefaultAuthGuard)
      .useValue(basicAuthGuard)
      .overrideGuard(ACGuard)
      .useValue(acGuard)
      .overrideInterceptor(AclFilterResponseInterceptor)
      .useValue(aclFilterResponseInterceptor)
      .overrideInterceptor(AclValidateRequestInterceptor)
      .useValue(aclValidateRequestInterceptor)
      .compile();

    app = moduleRef.createNestApplication();
    await app.init();
  });

  test("POST /purchaseInvoices", async () => {
    await request(app.getHttpServer())
      .post("/purchaseInvoices")
      .send(CREATE_INPUT)
      .expect(HttpStatus.CREATED)
      .expect({
        ...CREATE_RESULT,
        billDate: CREATE_RESULT.billDate.toISOString(),
        clearanceDate: CREATE_RESULT.clearanceDate.toISOString(),
        createdAt: CREATE_RESULT.createdAt.toISOString(),
        creation: CREATE_RESULT.creation.toISOString(),
        dueDate: CREATE_RESULT.dueDate.toISOString(),
        fromDate: CREATE_RESULT.fromDate.toISOString(),
        modified: CREATE_RESULT.modified.toISOString(),
        postingDate: CREATE_RESULT.postingDate.toISOString(),
        releaseDate: CREATE_RESULT.releaseDate.toISOString(),
        toDate: CREATE_RESULT.toDate.toISOString(),
        updatedAt: CREATE_RESULT.updatedAt.toISOString(),
      });
  });

  test("GET /purchaseInvoices", async () => {
    await request(app.getHttpServer())
      .get("/purchaseInvoices")
      .expect(HttpStatus.OK)
      .expect([
        {
          ...FIND_MANY_RESULT[0],
          billDate: FIND_MANY_RESULT[0].billDate.toISOString(),
          clearanceDate: FIND_MANY_RESULT[0].clearanceDate.toISOString(),
          createdAt: FIND_MANY_RESULT[0].createdAt.toISOString(),
          creation: FIND_MANY_RESULT[0].creation.toISOString(),
          dueDate: FIND_MANY_RESULT[0].dueDate.toISOString(),
          fromDate: FIND_MANY_RESULT[0].fromDate.toISOString(),
          modified: FIND_MANY_RESULT[0].modified.toISOString(),
          postingDate: FIND_MANY_RESULT[0].postingDate.toISOString(),
          releaseDate: FIND_MANY_RESULT[0].releaseDate.toISOString(),
          toDate: FIND_MANY_RESULT[0].toDate.toISOString(),
          updatedAt: FIND_MANY_RESULT[0].updatedAt.toISOString(),
        },
      ]);
  });

  test("GET /purchaseInvoices/:id non existing", async () => {
    await request(app.getHttpServer())
      .get(`${"/purchaseInvoices"}/${nonExistingId}`)
      .expect(HttpStatus.NOT_FOUND)
      .expect({
        statusCode: HttpStatus.NOT_FOUND,
        message: `No resource was found for {"${"id"}":"${nonExistingId}"}`,
        error: "Not Found",
      });
  });

  test("GET /purchaseInvoices/:id existing", async () => {
    await request(app.getHttpServer())
      .get(`${"/purchaseInvoices"}/${existingId}`)
      .expect(HttpStatus.OK)
      .expect({
        ...FIND_ONE_RESULT,
        billDate: FIND_ONE_RESULT.billDate.toISOString(),
        clearanceDate: FIND_ONE_RESULT.clearanceDate.toISOString(),
        createdAt: FIND_ONE_RESULT.createdAt.toISOString(),
        creation: FIND_ONE_RESULT.creation.toISOString(),
        dueDate: FIND_ONE_RESULT.dueDate.toISOString(),
        fromDate: FIND_ONE_RESULT.fromDate.toISOString(),
        modified: FIND_ONE_RESULT.modified.toISOString(),
        postingDate: FIND_ONE_RESULT.postingDate.toISOString(),
        releaseDate: FIND_ONE_RESULT.releaseDate.toISOString(),
        toDate: FIND_ONE_RESULT.toDate.toISOString(),
        updatedAt: FIND_ONE_RESULT.updatedAt.toISOString(),
      });
  });

  test("POST /purchaseInvoices existing resource", async () => {
    const agent = request(app.getHttpServer());
    await agent
      .post("/purchaseInvoices")
      .send(CREATE_INPUT)
      .expect(HttpStatus.CREATED)
      .expect({
        ...CREATE_RESULT,
        billDate: CREATE_RESULT.billDate.toISOString(),
        clearanceDate: CREATE_RESULT.clearanceDate.toISOString(),
        createdAt: CREATE_RESULT.createdAt.toISOString(),
        creation: CREATE_RESULT.creation.toISOString(),
        dueDate: CREATE_RESULT.dueDate.toISOString(),
        fromDate: CREATE_RESULT.fromDate.toISOString(),
        modified: CREATE_RESULT.modified.toISOString(),
        postingDate: CREATE_RESULT.postingDate.toISOString(),
        releaseDate: CREATE_RESULT.releaseDate.toISOString(),
        toDate: CREATE_RESULT.toDate.toISOString(),
        updatedAt: CREATE_RESULT.updatedAt.toISOString(),
      })
      .then(function () {
        agent
          .post("/purchaseInvoices")
          .send(CREATE_INPUT)
          .expect(HttpStatus.CONFLICT)
          .expect({
            statusCode: HttpStatus.CONFLICT,
          });
      });
  });

  afterAll(async () => {
    await app.close();
  });
});
