export type CustomerGroup = {
  createdAt: Date;
  creation: Date | null;
  customerGroupName: string | null;
  defaultPriceList: string | null;
  docstatus: number | null;
  id: string;
  idx: number | null;
  isGroup: boolean | null;
  lft: number | null;
  modified: Date | null;
  modifiedBy: string | null;
  name: string | null;
  oldParent: string | null;
  owner: string | null;
  parentCustomerGroup: string | null;
  paymentTerms: string | null;
  rgt: number | null;
  updatedAt: Date;
};
