export type BomScrapItem = {
  amount: number | null;
  baseAmount: number | null;
  baseRate: number | null;
  createdAt: Date;
  creation: Date | null;
  docstatus: number | null;
  id: string;
  idx: number | null;
  itemCode: string | null;
  itemName: string | null;
  modified: Date | null;
  modifiedBy: string | null;
  name: string | null;
  owner: string | null;
  parent: string | null;
  parentfield: string | null;
  parenttype: string | null;
  rate: number | null;
  stockQty: number | null;
  stockUom: string | null;
  updatedAt: Date;
};
