export type BomScrapItemUpdateInput = {
  amount?: number | null;
  baseAmount?: number | null;
  baseRate?: number | null;
  creation?: Date | null;
  docstatus?: number | null;
  idx?: number | null;
  itemCode?: string | null;
  itemName?: string | null;
  modified?: Date | null;
  modifiedBy?: string | null;
  name?: string | null;
  owner?: string | null;
  parent?: string | null;
  parentfield?: string | null;
  parenttype?: string | null;
  rate?: number | null;
  stockQty?: number | null;
  stockUom?: string | null;
};
