/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  SubcontractingOrderSuppliedItem as PrismaSubcontractingOrderSuppliedItem,
} from "@prisma/client";

export class SubcontractingOrderSuppliedItemServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.SubcontractingOrderSuppliedItemCountArgs, "select">
  ): Promise<number> {
    return this.prisma.subcontractingOrderSuppliedItem.count(args);
  }

  async subcontractingOrderSuppliedItems(
    args: Prisma.SubcontractingOrderSuppliedItemFindManyArgs
  ): Promise<PrismaSubcontractingOrderSuppliedItem[]> {
    return this.prisma.subcontractingOrderSuppliedItem.findMany(args);
  }
  async subcontractingOrderSuppliedItem(
    args: Prisma.SubcontractingOrderSuppliedItemFindUniqueArgs
  ): Promise<PrismaSubcontractingOrderSuppliedItem | null> {
    return this.prisma.subcontractingOrderSuppliedItem.findUnique(args);
  }
  async createSubcontractingOrderSuppliedItem(
    args: Prisma.SubcontractingOrderSuppliedItemCreateArgs
  ): Promise<PrismaSubcontractingOrderSuppliedItem> {
    return this.prisma.subcontractingOrderSuppliedItem.create(args);
  }
  async updateSubcontractingOrderSuppliedItem(
    args: Prisma.SubcontractingOrderSuppliedItemUpdateArgs
  ): Promise<PrismaSubcontractingOrderSuppliedItem> {
    return this.prisma.subcontractingOrderSuppliedItem.update(args);
  }
  async deleteSubcontractingOrderSuppliedItem(
    args: Prisma.SubcontractingOrderSuppliedItemDeleteArgs
  ): Promise<PrismaSubcontractingOrderSuppliedItem> {
    return this.prisma.subcontractingOrderSuppliedItem.delete(args);
  }
}
