export type CustomDocPerm = {
  amend: boolean | null;
  cancel: boolean | null;
  create: boolean | null;
  createdAt: Date;
  creation: Date | null;
  deleteField: boolean | null;
  docstatus: number | null;
  email: boolean | null;
  exportField: boolean | null;
  id: string;
  idx: number | null;
  ifOwner: boolean | null;
  importField: boolean | null;
  modified: Date | null;
  modifiedBy: string | null;
  name: string | null;
  owner: string | null;
  parent: string | null;
  permlevel: number | null;
  print: boolean | null;
  read: boolean | null;
  report: boolean | null;
  role: string | null;
  selectField: boolean | null;
  share: boolean | null;
  submit: boolean | null;
  updatedAt: Date;
  write: boolean | null;
};
