import { BooleanNullableFilter } from "../../util/BooleanNullableFilter";
import { FloatNullableFilter } from "../../util/FloatNullableFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { DateTimeNullableFilter } from "../../util/DateTimeNullableFilter";
import { IntNullableFilter } from "../../util/IntNullableFilter";
import { StringFilter } from "../../util/StringFilter";

export type BomItemWhereInput = {
  allowAlternativeItem?: BooleanNullableFilter;
  amount?: FloatNullableFilter;
  baseAmount?: FloatNullableFilter;
  baseRate?: FloatNullableFilter;
  bomNo?: StringNullableFilter;
  conversionFactor?: FloatNullableFilter;
  creation?: DateTimeNullableFilter;
  description?: StringNullableFilter;
  doNotExplode?: BooleanNullableFilter;
  docstatus?: IntNullableFilter;
  hasVariants?: BooleanNullableFilter;
  id?: StringFilter;
  idx?: IntNullableFilter;
  image?: StringNullableFilter;
  includeItemInManufacturing?: BooleanNullableFilter;
  isStockItem?: BooleanNullableFilter;
  itemCode?: StringNullableFilter;
  itemName?: StringNullableFilter;
  modified?: DateTimeNullableFilter;
  modifiedBy?: StringNullableFilter;
  name?: StringNullableFilter;
  operation?: StringNullableFilter;
  originalItem?: StringNullableFilter;
  owner?: StringNullableFilter;
  parent?: StringNullableFilter;
  parentfield?: StringNullableFilter;
  parenttype?: StringNullableFilter;
  qty?: FloatNullableFilter;
  qtyConsumedPerUnit?: FloatNullableFilter;
  rate?: FloatNullableFilter;
  sourceWarehouse?: StringNullableFilter;
  sourcedBySupplier?: BooleanNullableFilter;
  stockQty?: FloatNullableFilter;
  stockUom?: StringNullableFilter;
  uom?: StringNullableFilter;
};
