import { SortOrder } from "../../util/SortOrder";

export type BomItemOrderByInput = {
  allowAlternativeItem?: SortOrder;
  amount?: SortOrder;
  baseAmount?: SortOrder;
  baseRate?: SortOrder;
  bomNo?: SortOrder;
  conversionFactor?: SortOrder;
  createdAt?: SortOrder;
  creation?: SortOrder;
  description?: SortOrder;
  doNotExplode?: SortOrder;
  docstatus?: SortOrder;
  hasVariants?: SortOrder;
  id?: SortOrder;
  idx?: SortOrder;
  image?: SortOrder;
  includeItemInManufacturing?: SortOrder;
  isStockItem?: SortOrder;
  itemCode?: SortOrder;
  itemName?: SortOrder;
  modified?: SortOrder;
  modifiedBy?: SortOrder;
  name?: SortOrder;
  operation?: SortOrder;
  originalItem?: SortOrder;
  owner?: SortOrder;
  parent?: SortOrder;
  parentfield?: SortOrder;
  parenttype?: SortOrder;
  qty?: SortOrder;
  qtyConsumedPerUnit?: SortOrder;
  rate?: SortOrder;
  sourceWarehouse?: SortOrder;
  sourcedBySupplier?: SortOrder;
  stockQty?: SortOrder;
  stockUom?: SortOrder;
  uom?: SortOrder;
  updatedAt?: SortOrder;
};
