export type AccountingDimensionDetail = {
  automaticallyPostBalancingAccountingEntry: number | null;
  company: string | null;
  createdAt: Date;
  creation: Date | null;
  defaultDimension: string | null;
  docstatus: number | null;
  id: string;
  idx: number | null;
  mandatoryForBs: number | null;
  mandatoryForPl: number | null;
  modified: Date | null;
  modifiedBy: string | null;
  name: string | null;
  offsettingAccount: string | null;
  owner: string | null;
  parent: string | null;
  parentfield: string | null;
  parenttype: string | null;
  referenceDocument: string | null;
  updatedAt: Date;
};
