export type BomUpdateLog = {
  amendedFrom: string | null;
  createdAt: Date;
  creation: Date | null;
  currentBom: string | null;
  currentLevel: number | null;
  docstatus: number | null;
  errorLog: string | null;
  id: string;
  idx: number | null;
  modified: Date | null;
  modifiedBy: string | null;
  name: string | null;
  newBom: string | null;
  owner: string | null;
  processedBoms: string | null;
  status: string | null;
  updateType: string | null;
  updatedAt: Date;
};
