export type DocTypeLinkCreateInput = {
  creation?: Date | null;
  custom?: number | null;
  docstatus?: number | null;
  group?: string | null;
  hidden?: number | null;
  idx?: number | null;
  isChildTable?: number | null;
  linkDoctype?: string | null;
  linkFieldname?: string | null;
  modified?: Date | null;
  modifiedBy?: string | null;
  name?: string | null;
  owner?: string | null;
  parent?: string | null;
  parentDoctype?: string | null;
  parentfield?: string | null;
  parenttype?: string | null;
  tableFieldname?: string | null;
};
