/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { ExplorationBasexpService } from "../explorationBasexp.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ExplorationBasexpCreateInput } from "./ExplorationBasexpCreateInput";
import { ExplorationBasexp } from "./ExplorationBasexp";
import { ExplorationBasexpFindManyArgs } from "./ExplorationBasexpFindManyArgs";
import { ExplorationBasexpWhereUniqueInput } from "./ExplorationBasexpWhereUniqueInput";
import { ExplorationBasexpUpdateInput } from "./ExplorationBasexpUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ExplorationBasexpControllerBase {
  constructor(
    protected readonly service: ExplorationBasexpService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: ExplorationBasexp })
  @nestAccessControl.UseRoles({
    resource: "ExplorationBasexp",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: ExplorationBasexpCreateInput,
  })
  async createExplorationBasexp(
    @common.Body() data: ExplorationBasexpCreateInput
  ): Promise<ExplorationBasexp> {
    return await this.service.createExplorationBasexp({
      data: data,
      select: {
        basexp: true,
        createdAt: true,
        id: true,
        level: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [ExplorationBasexp] })
  @ApiNestedQuery(ExplorationBasexpFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "ExplorationBasexp",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async explorationBasexps(
    @common.Req() request: Request
  ): Promise<ExplorationBasexp[]> {
    const args = plainToClass(ExplorationBasexpFindManyArgs, request.query);
    return this.service.explorationBasexps({
      ...args,
      select: {
        basexp: true,
        createdAt: true,
        id: true,
        level: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: ExplorationBasexp })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ExplorationBasexp",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async explorationBasexp(
    @common.Param() params: ExplorationBasexpWhereUniqueInput
  ): Promise<ExplorationBasexp | null> {
    const result = await this.service.explorationBasexp({
      where: params,
      select: {
        basexp: true,
        createdAt: true,
        id: true,
        level: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: ExplorationBasexp })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ExplorationBasexp",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: ExplorationBasexpUpdateInput,
  })
  async updateExplorationBasexp(
    @common.Param() params: ExplorationBasexpWhereUniqueInput,
    @common.Body() data: ExplorationBasexpUpdateInput
  ): Promise<ExplorationBasexp | null> {
    try {
      return await this.service.updateExplorationBasexp({
        where: params,
        data: data,
        select: {
          basexp: true,
          createdAt: true,
          id: true,
          level: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: ExplorationBasexp })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ExplorationBasexp",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteExplorationBasexp(
    @common.Param() params: ExplorationBasexpWhereUniqueInput
  ): Promise<ExplorationBasexp | null> {
    try {
      return await this.service.deleteExplorationBasexp({
        where: params,
        select: {
          basexp: true,
          createdAt: true,
          id: true,
          level: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
