export type AuthorizationRule = {
  approvingRole: string | null;
  approvingUser: string | null;
  basedOn: string | null;
  company: string | null;
  createdAt: Date;
  creation: Date | null;
  customerOrItem: string | null;
  docstatus: number | null;
  id: string;
  idx: number | null;
  masterName: string | null;
  modified: Date | null;
  modifiedBy: string | null;
  name: string | null;
  owner: string | null;
  systemRole: string | null;
  systemUser: string | null;
  toDesignation: string | null;
  toEmp: string | null;
  transaction: string | null;
  updatedAt: Date;
  value: number | null;
};
