export type BlanketOrderItem = {
  createdAt: Date;
  creation: Date | null;
  docstatus: number | null;
  id: string;
  idx: number | null;
  itemCode: string | null;
  itemName: string | null;
  modified: Date | null;
  modifiedBy: string | null;
  name: string | null;
  orderedQty: number | null;
  owner: string | null;
  parent: string | null;
  parentfield: string | null;
  parenttype: string | null;
  partyItemCode: string | null;
  qty: number | null;
  rate: number | null;
  termsAndConditions: string | null;
  updatedAt: Date;
};
