import { FloatNullableFilter } from "../../util/FloatNullableFilter";
import { BooleanNullableFilter } from "../../util/BooleanNullableFilter";
import { DateTimeNullableFilter } from "../../util/DateTimeNullableFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { IntNullableFilter } from "../../util/IntNullableFilter";
import { StringFilter } from "../../util/StringFilter";

export type BomCreatorItemWhereInput = {
  amount?: FloatNullableFilter;
  baseAmount?: FloatNullableFilter;
  baseRate?: FloatNullableFilter;
  bomCreated?: BooleanNullableFilter;
  conversionFactor?: FloatNullableFilter;
  creation?: DateTimeNullableFilter;
  description?: StringNullableFilter;
  doNotExplode?: BooleanNullableFilter;
  docstatus?: IntNullableFilter;
  fgItem?: StringNullableFilter;
  fgReferenceId?: StringNullableFilter;
  id?: StringFilter;
  idx?: IntNullableFilter;
  instruction?: StringNullableFilter;
  isExpandable?: BooleanNullableFilter;
  itemCode?: StringNullableFilter;
  itemGroup?: StringNullableFilter;
  itemName?: StringNullableFilter;
  modified?: DateTimeNullableFilter;
  modifiedBy?: StringNullableFilter;
  name?: StringNullableFilter;
  owner?: StringNullableFilter;
  parent?: StringNullableFilter;
  parentRowNo?: StringNullableFilter;
  parentfield?: StringNullableFilter;
  parenttype?: StringNullableFilter;
  qty?: FloatNullableFilter;
  rate?: FloatNullableFilter;
  sourceWarehouse?: StringNullableFilter;
  sourcedBySupplier?: BooleanNullableFilter;
  stockQty?: FloatNullableFilter;
  stockUom?: StringNullableFilter;
  uom?: StringNullableFilter;
};
