export type BomCreatorItem = {
  amount: number | null;
  baseAmount: number | null;
  baseRate: number | null;
  bomCreated: boolean | null;
  conversionFactor: number | null;
  createdAt: Date;
  creation: Date | null;
  description: string | null;
  doNotExplode: boolean | null;
  docstatus: number | null;
  fgItem: string | null;
  fgReferenceId: string | null;
  id: string;
  idx: number | null;
  instruction: string | null;
  isExpandable: boolean | null;
  itemCode: string | null;
  itemGroup: string | null;
  itemName: string | null;
  modified: Date | null;
  modifiedBy: string | null;
  name: string | null;
  owner: string | null;
  parent: string | null;
  parentRowNo: string | null;
  parentfield: string | null;
  parenttype: string | null;
  qty: number | null;
  rate: number | null;
  sourceWarehouse: string | null;
  sourcedBySupplier: boolean | null;
  stockQty: number | null;
  stockUom: string | null;
  uom: string | null;
  updatedAt: Date;
};
