import { SortOrder } from "../../util/SortOrder";

export type BomCreatorItemOrderByInput = {
  amount?: SortOrder;
  baseAmount?: SortOrder;
  baseRate?: SortOrder;
  bomCreated?: SortOrder;
  conversionFactor?: SortOrder;
  createdAt?: SortOrder;
  creation?: SortOrder;
  description?: SortOrder;
  doNotExplode?: SortOrder;
  docstatus?: SortOrder;
  fgItem?: SortOrder;
  fgReferenceId?: SortOrder;
  id?: SortOrder;
  idx?: SortOrder;
  instruction?: SortOrder;
  isExpandable?: SortOrder;
  itemCode?: SortOrder;
  itemGroup?: SortOrder;
  itemName?: SortOrder;
  modified?: SortOrder;
  modifiedBy?: SortOrder;
  name?: SortOrder;
  owner?: SortOrder;
  parent?: SortOrder;
  parentRowNo?: SortOrder;
  parentfield?: SortOrder;
  parenttype?: SortOrder;
  qty?: SortOrder;
  rate?: SortOrder;
  sourceWarehouse?: SortOrder;
  sourcedBySupplier?: SortOrder;
  stockQty?: SortOrder;
  stockUom?: SortOrder;
  uom?: SortOrder;
  updatedAt?: SortOrder;
};
