export type AssetCategoryAccount = {
  accumulatedDepreciationAccount: string | null;
  capitalWorkInProgressAccount: string | null;
  companyName: string | null;
  createdAt: Date;
  creation: Date | null;
  depreciationExpenseAccount: string | null;
  docstatus: number | null;
  fixedAssetAccount: string | null;
  id: string;
  idx: number | null;
  modified: Date | null;
  modifiedBy: string | null;
  name: string | null;
  owner: string | null;
  parent: string | null;
  parentfield: string | null;
  parenttype: string | null;
  updatedAt: Date;
};
