import { SortOrder } from "../../util/SortOrder";

export type ProductionPlanOrderByInput = {
  amendedFrom?: SortOrder;
  combineItems?: SortOrder;
  combineSubItems?: SortOrder;
  company?: SortOrder;
  considerMinimumOrderQty?: SortOrder;
  createdAt?: SortOrder;
  creation?: SortOrder;
  customer?: SortOrder;
  docstatus?: SortOrder;
  forWarehouse?: SortOrder;
  fromDate?: SortOrder;
  fromDeliveryDate?: SortOrder;
  getItemsFrom?: SortOrder;
  id?: SortOrder;
  idx?: SortOrder;
  ignoreExistingOrderedQty?: SortOrder;
  includeNonStockItems?: SortOrder;
  includeSafetyStock?: SortOrder;
  includeSubcontractedItems?: SortOrder;
  itemCode?: SortOrder;
  modified?: SortOrder;
  modifiedBy?: SortOrder;
  name?: SortOrder;
  namingSeries?: SortOrder;
  owner?: SortOrder;
  postingDate?: SortOrder;
  project?: SortOrder;
  salesOrderStatus?: SortOrder;
  skipAvailableSubAssemblyItem?: SortOrder;
  status?: SortOrder;
  subAssemblyWarehouse?: SortOrder;
  toDate?: SortOrder;
  toDeliveryDate?: SortOrder;
  totalPlannedQty?: SortOrder;
  totalProducedQty?: SortOrder;
  updatedAt?: SortOrder;
  warehouse?: SortOrder;
};
