import { StringNullableFilter } from "../../util/StringNullableFilter";
import { IntNullableFilter } from "../../util/IntNullableFilter";
import { DateTimeNullableFilter } from "../../util/DateTimeNullableFilter";
import { StringFilter } from "../../util/StringFilter";
import { FloatNullableFilter } from "../../util/FloatNullableFilter";

export type ProductionPlanWhereInput = {
  amendedFrom?: StringNullableFilter;
  combineItems?: IntNullableFilter;
  combineSubItems?: IntNullableFilter;
  company?: StringNullableFilter;
  considerMinimumOrderQty?: IntNullableFilter;
  creation?: DateTimeNullableFilter;
  customer?: StringNullableFilter;
  docstatus?: IntNullableFilter;
  forWarehouse?: StringNullableFilter;
  fromDate?: DateTimeNullableFilter;
  fromDeliveryDate?: DateTimeNullableFilter;
  getItemsFrom?: StringNullableFilter;
  id?: StringFilter;
  idx?: IntNullableFilter;
  ignoreExistingOrderedQty?: IntNullableFilter;
  includeNonStockItems?: IntNullableFilter;
  includeSafetyStock?: IntNullableFilter;
  includeSubcontractedItems?: IntNullableFilter;
  itemCode?: StringNullableFilter;
  modified?: DateTimeNullableFilter;
  modifiedBy?: StringNullableFilter;
  name?: StringNullableFilter;
  namingSeries?: StringNullableFilter;
  owner?: StringNullableFilter;
  postingDate?: DateTimeNullableFilter;
  project?: StringNullableFilter;
  salesOrderStatus?: StringNullableFilter;
  skipAvailableSubAssemblyItem?: IntNullableFilter;
  status?: StringNullableFilter;
  subAssemblyWarehouse?: StringNullableFilter;
  toDate?: DateTimeNullableFilter;
  toDeliveryDate?: DateTimeNullableFilter;
  totalPlannedQty?: FloatNullableFilter;
  totalProducedQty?: FloatNullableFilter;
  warehouse?: StringNullableFilter;
};
