export type PaymentOrderReference = {
  account: string | null;
  amount: number | null;
  bankAccount: string | null;
  createdAt: Date;
  creation: Date | null;
  docstatus: number | null;
  id: string;
  idx: number | null;
  modeOfPayment: string | null;
  modified: Date | null;
  modifiedBy: string | null;
  name: string | null;
  owner: string | null;
  parent: string | null;
  parentfield: string | null;
  parenttype: string | null;
  paymentReference: string | null;
  paymentRequest: string | null;
  referenceDoctype: string | null;
  referenceName: string | null;
  supplier: string | null;
  updatedAt: Date;
};
