import { SortOrder } from "../../util/SortOrder";

export type DunningOrderByInput = {
  addressDisplay?: SortOrder;
  amendedFrom?: SortOrder;
  baseDunningAmount?: SortOrder;
  bodyText?: SortOrder;
  closingText?: SortOrder;
  company?: SortOrder;
  companyAddress?: SortOrder;
  companyAddressDisplay?: SortOrder;
  contactDisplay?: SortOrder;
  contactEmail?: SortOrder;
  contactMobile?: SortOrder;
  contactPerson?: SortOrder;
  conversionRate?: SortOrder;
  costCenter?: SortOrder;
  createdAt?: SortOrder;
  creation?: SortOrder;
  currency?: SortOrder;
  customer?: SortOrder;
  customerAddress?: SortOrder;
  customerName?: SortOrder;
  docstatus?: SortOrder;
  dunningAmount?: SortOrder;
  dunningFee?: SortOrder;
  dunningType?: SortOrder;
  grandTotal?: SortOrder;
  id?: SortOrder;
  idx?: SortOrder;
  incomeAccount?: SortOrder;
  language?: SortOrder;
  letterHead?: SortOrder;
  modified?: SortOrder;
  modifiedBy?: SortOrder;
  name?: SortOrder;
  namingSeries?: SortOrder;
  owner?: SortOrder;
  postingDate?: SortOrder;
  postingTime?: SortOrder;
  rateOfInterest?: SortOrder;
  spacer?: SortOrder;
  status?: SortOrder;
  totalInterest?: SortOrder;
  totalOutstanding?: SortOrder;
  updatedAt?: SortOrder;
};
