export type TbClreDedRimexPrngPdls = {
  cmdtClsfSpelCd: string | null;
  createdAt: Date;
  delYn: string | null;
  dlngPdlsNm: string | null;
  frstRegstId: string | null;
  frstRgsrDttm: Date | null;
  hsCd: string | null;
  hsErrPvntVal: string | null;
  id: string;
  lastChgDttm: Date | null;
  lastChprId: string | null;
  mdfyDgcnt: number | null;
  orcyCntyCd: string | null;
  pdlsNm: string | null;
  pdlsNtwg: number | null;
  pdlsTtwg: number | null;
  prngPdlsNo: string | null;
  qty: number | null;
  qtyUtCd: string | null;
  reffNo: string | null;
  updatedAt: Date;
};
