import { StringNullableFilter } from "../../util/StringNullableFilter";
import { IntNullableFilter } from "../../util/IntNullableFilter";
import { DateTimeNullableFilter } from "../../util/DateTimeNullableFilter";
import { StringFilter } from "../../util/StringFilter";
import { FloatNullableFilter } from "../../util/FloatNullableFilter";

export type PosProfileWhereInput = {
  accountForChangeAmount?: StringNullableFilter;
  allowDiscountChange?: IntNullableFilter;
  allowRateChange?: IntNullableFilter;
  applyDiscountOn?: StringNullableFilter;
  autoAddItemToCart?: IntNullableFilter;
  campaign?: StringNullableFilter;
  company?: StringNullableFilter;
  companyAddress?: StringNullableFilter;
  costCenter?: StringNullableFilter;
  country?: StringNullableFilter;
  creation?: DateTimeNullableFilter;
  currency?: StringNullableFilter;
  customer?: StringNullableFilter;
  disableRoundedTotal?: IntNullableFilter;
  disabled?: IntNullableFilter;
  docStatus?: IntNullableFilter;
  expenseAccount?: StringNullableFilter;
  hideImages?: IntNullableFilter;
  hideUnavailableItems?: IntNullableFilter;
  id?: StringFilter;
  idx?: IntNullableFilter;
  ignorePricingRule?: IntNullableFilter;
  incomeAccount?: StringNullableFilter;
  letterHead?: StringNullableFilter;
  modified?: DateTimeNullableFilter;
  modifiedBy?: StringNullableFilter;
  name?: StringNullableFilter;
  owner?: StringNullableFilter;
  printFormat?: StringNullableFilter;
  selectPrintHeading?: StringNullableFilter;
  sellingPriceList?: StringNullableFilter;
  taxCategory?: StringNullableFilter;
  taxesAndCharges?: StringNullableFilter;
  tcName?: StringNullableFilter;
  updateStock?: IntNullableFilter;
  validateStockOnSave?: IntNullableFilter;
  warehouse?: StringNullableFilter;
  writeOffAccount?: StringNullableFilter;
  writeOffCostCenter?: StringNullableFilter;
  writeOffLimit?: FloatNullableFilter;
};
