import { SortOrder } from "../../util/SortOrder";

export type PosProfileOrderByInput = {
  accountForChangeAmount?: SortOrder;
  allowDiscountChange?: SortOrder;
  allowRateChange?: SortOrder;
  applyDiscountOn?: SortOrder;
  autoAddItemToCart?: SortOrder;
  campaign?: SortOrder;
  company?: SortOrder;
  companyAddress?: SortOrder;
  costCenter?: SortOrder;
  country?: SortOrder;
  createdAt?: SortOrder;
  creation?: SortOrder;
  currency?: SortOrder;
  customer?: SortOrder;
  disableRoundedTotal?: SortOrder;
  disabled?: SortOrder;
  docStatus?: SortOrder;
  expenseAccount?: SortOrder;
  hideImages?: SortOrder;
  hideUnavailableItems?: SortOrder;
  id?: SortOrder;
  idx?: SortOrder;
  ignorePricingRule?: SortOrder;
  incomeAccount?: SortOrder;
  letterHead?: SortOrder;
  modified?: SortOrder;
  modifiedBy?: SortOrder;
  name?: SortOrder;
  owner?: SortOrder;
  printFormat?: SortOrder;
  selectPrintHeading?: SortOrder;
  sellingPriceList?: SortOrder;
  taxCategory?: SortOrder;
  taxesAndCharges?: SortOrder;
  tcName?: SortOrder;
  updateStock?: SortOrder;
  updatedAt?: SortOrder;
  validateStockOnSave?: SortOrder;
  warehouse?: SortOrder;
  writeOffAccount?: SortOrder;
  writeOffCostCenter?: SortOrder;
  writeOffLimit?: SortOrder;
};
