export type PurchaseTaxesAndCharges = {
  accountCurrency: string | null;
  accountHead: string | null;
  addDeductTax: string | null;
  baseTaxAmount: number | null;
  baseTaxAmountAfterDiscountAmount: number | null;
  baseTotal: number | null;
  category: string | null;
  chargeType: string | null;
  costCenter: string | null;
  createdAt: Date;
  creation: Date | null;
  description: string | null;
  docstatus: number | null;
  id: string;
  idx: number | null;
  includedInPaidAmount: number | null;
  includedInPrintRate: number | null;
  isTaxWithholdingAccount: number | null;
  itemWiseTaxDetail: string | null;
  modified: Date | null;
  modifiedBy: string | null;
  name: string | null;
  owner: string | null;
  parent: string | null;
  parentField: string | null;
  parentType: string | null;
  rate: number | null;
  rowId: string | null;
  taxAmount: number | null;
  taxAmountAfterDiscountAmount: number | null;
  total: number | null;
  updatedAt: Date;
};
