export type BankGuarantee = {
  account: string | null;
  amendedFrom: string | null;
  amount: number | null;
  bank: string | null;
  bankAccount: string | null;
  bankAccountNo: string | null;
  bankGuaranteeNumber: string | null;
  bgType: string | null;
  branchCode: string | null;
  charges: number | null;
  createdAt: Date;
  creation: Date | null;
  customer: string | null;
  docstatus: number | null;
  endDate: Date | null;
  fixedDepositNumber: string | null;
  iban: string | null;
  id: string;
  idx: number | null;
  marginMoney: number | null;
  modified: Date | null;
  modifiedBy: string | null;
  moreInformation: string | null;
  name: string | null;
  nameOfBeneficiary: string | null;
  owner: string | null;
  project: string | null;
  referenceDocname: string | null;
  referenceDoctype: string | null;
  startDate: Date | null;
  supplier: string | null;
  swiftNumber: string | null;
  updatedAt: Date;
  validity: number | null;
};
