export type LandedCostTaxesAndCharges = {
  accountCurrency: string | null;
  amount: number | null;
  baseAmount: number | null;
  createdAt: Date;
  creation: Date | null;
  description: string | null;
  docstatus: number | null;
  exchangeRate: number | null;
  expenseAccount: string | null;
  id: string;
  idx: number | null;
  modified: Date | null;
  modifiedBy: string | null;
  name: string | null;
  owner: string | null;
  parent: string | null;
  parentfield: string | null;
  parenttype: string | null;
  updatedAt: Date;
};
