import { StringNullableFilter } from "../../util/StringNullableFilter";
import { DateTimeNullableFilter } from "../../util/DateTimeNullableFilter";
import { IntNullableFilter } from "../../util/IntNullableFilter";
import { FloatNullableFilter } from "../../util/FloatNullableFilter";
import { StringFilter } from "../../util/StringFilter";

export type PaymentRequestWhereInput = {
  account?: StringNullableFilter;
  amendedFrom?: StringNullableFilter;
  bank?: StringNullableFilter;
  bankAccount?: StringNullableFilter;
  bankAccountNo?: StringNullableFilter;
  branchCode?: StringNullableFilter;
  company?: StringNullableFilter;
  costCenter?: StringNullableFilter;
  creation?: DateTimeNullableFilter;
  currency?: StringNullableFilter;
  docstatus?: IntNullableFilter;
  emailTo?: StringNullableFilter;
  grandTotal?: FloatNullableFilter;
  iban?: StringNullableFilter;
  id?: StringFilter;
  idx?: IntNullableFilter;
  isASubscription?: IntNullableFilter;
  makeSalesInvoice?: IntNullableFilter;
  message?: StringNullableFilter;
  modeOfPayment?: StringNullableFilter;
  modified?: DateTimeNullableFilter;
  modifiedBy?: StringNullableFilter;
  muteEmail?: IntNullableFilter;
  name?: StringNullableFilter;
  namingSeries?: StringNullableFilter;
  owner?: StringNullableFilter;
  party?: StringNullableFilter;
  partyType?: StringNullableFilter;
  paymentAccount?: StringNullableFilter;
  paymentChannel?: StringNullableFilter;
  paymentGateway?: StringNullableFilter;
  paymentGatewayAccount?: StringNullableFilter;
  paymentOrder?: StringNullableFilter;
  paymentRequestType?: StringNullableFilter;
  paymentUrl?: StringNullableFilter;
  printFormat?: StringNullableFilter;
  project?: StringNullableFilter;
  referenceDoctype?: StringNullableFilter;
  referenceName?: StringNullableFilter;
  status?: StringNullableFilter;
  subject?: StringNullableFilter;
  swiftNumber?: StringNullableFilter;
  transactionDate?: DateTimeNullableFilter;
};
