import { SortOrder } from "../../util/SortOrder";

export type TbClreDedMdlStszOrderByInput = {
  cachAmt?: SortOrder;
  cachCurrCd?: SortOrder;
  cachFxrt?: SortOrder;
  cachNcyAmt?: SortOrder;
  createdAt?: SortOrder;
  ddctAmt?: SortOrder;
  ddctCurrCd?: SortOrder;
  ddctFxrt?: SortOrder;
  ddctNcyAmt?: SortOrder;
  ddctRt?: SortOrder;
  delYn?: SortOrder;
  frstRegstId?: SortOrder;
  frstRgsrDttm?: SortOrder;
  id?: SortOrder;
  indrPymnTamt?: SortOrder;
  infeeAmt?: SortOrder;
  infeeCurrCd?: SortOrder;
  infeeFxrt?: SortOrder;
  infeeNcyAmt?: SortOrder;
  ingrNm?: SortOrder;
  invcAmt?: SortOrder;
  invcCurrCd?: SortOrder;
  invcFxrt?: SortOrder;
  invcNcyAmt?: SortOrder;
  invcUsdAmt?: SortOrder;
  lastChgDttm?: SortOrder;
  lastChprId?: SortOrder;
  mdfyDgcnt?: SortOrder;
  mdlStszNm?: SortOrder;
  mdlStszNo?: SortOrder;
  otcstAmt?: SortOrder;
  otcstCurrCd?: SortOrder;
  otcstFxrt?: SortOrder;
  otcstNcyAmt?: SortOrder;
  pdlsNo?: SortOrder;
  qty?: SortOrder;
  qtyUtCd?: SortOrder;
  reffNo?: SortOrder;
  ttxbsNcyAmt?: SortOrder;
  ttxbsUsdAmt?: SortOrder;
  tvlutNcyAmt?: SortOrder;
  tvlutUsdAmt?: SortOrder;
  updatedAt?: SortOrder;
  utPrc?: SortOrder;
};
