import { FloatNullableFilter } from "../../util/FloatNullableFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { DateTimeNullableFilter } from "../../util/DateTimeNullableFilter";
import { StringFilter } from "../../util/StringFilter";
import { IntNullableFilter } from "../../util/IntNullableFilter";

export type TbClreDedPrcDclrPdlsWhereInput = {
  brngTrnpCst?: FloatNullableFilter;
  byerPymnCst?: FloatNullableFilter;
  delYn?: StringNullableFilter;
  frstRegstId?: StringNullableFilter;
  frstRgsrDttm?: DateTimeNullableFilter;
  id?: StringFilter;
  indrPymnTamt?: FloatNullableFilter;
  infeeAmt?: FloatNullableFilter;
  lastChgDttm?: DateTimeNullableFilter;
  lastChprId?: StringNullableFilter;
  loadCstAmt?: FloatNullableFilter;
  mdfyDgcnt?: IntNullableFilter;
  mdlStszNo?: StringNullableFilter;
  mdtnPcfeAmt?: FloatNullableFilter;
  mnfuSrvc_1Amt?: FloatNullableFilter;
  mnfuSrvc_2Amt?: FloatNullableFilter;
  mnfuSrvc_3Amt?: FloatNullableFilter;
  mnfuSrvc_4Amt?: FloatNullableFilter;
  otcstAmt?: FloatNullableFilter;
  pcfeAmt?: FloatNullableFilter;
  pcfeLcneAmt?: FloatNullableFilter;
  pckgAmt?: FloatNullableFilter;
  pdlsNo?: StringNullableFilter;
  pyrTrifAmt?: FloatNullableFilter;
  reffNo?: StringNullableFilter;
  resaleErnAmt?: FloatNullableFilter;
  techSpptCst?: FloatNullableFilter;
  trnpCstAmt?: FloatNullableFilter;
};
