export type ClreDedTaxCreateInput = {
  bscsTaxAmt?: number | null;
  bscsTxbsAmt?: number | null;
  bscsTxrt?: number | null;
  delYn?: string | null;
  frstRegstId?: string | null;
  frstRgsrDttm?: Date | null;
  lastChgDttm?: Date | null;
  lastChprId?: string | null;
  mdfyDgcnt?: number | null;
  mgDscnAplyAmt?: number | null;
  payKndCd?: string | null;
  payTaxAmt?: number | null;
  pdlsNo?: string | null;
  rdexAmt?: number | null;
  rdexBaseAmt?: number | null;
  rdexCd?: string | null;
  rdexPtCd?: string | null;
  rdexTxrt?: number | null;
  reffNo?: string | null;
  taxAmt?: number | null;
  taxCd?: string | null;
  tfrtCtgyCd?: string | null;
  txbsAmt?: number | null;
  txrt?: number | null;
};
