/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { GrpcMethod } from "@nestjs/microservices";
import { EventScriptsService } from "../eventScripts.service";
import { EventScriptsCreateInput } from "./EventScriptsCreateInput";
import { EventScriptsWhereInput } from "./EventScriptsWhereInput";
import { EventScriptsWhereUniqueInput } from "./EventScriptsWhereUniqueInput";
import { EventScriptsFindManyArgs } from "./EventScriptsFindManyArgs";
import { EventScriptsUpdateInput } from "./EventScriptsUpdateInput";
import { EventScripts } from "./EventScripts";

export class EventScriptsGrpcControllerBase {
  constructor(protected readonly service: EventScriptsService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: EventScripts })
  @GrpcMethod("EventScriptsService", "createEventScripts")
  async createEventScripts(
    @common.Body() data: EventScriptsCreateInput
  ): Promise<EventScripts> {
    return await this.service.createEventScripts({
      data: data,
      select: {
        command: true,
        comment: true,
        createdAt: true,
        dataint: true,
        datalong: true,
        datalong2: true,
        delay: true,
        id: true,
        o: true,
        updatedAt: true,
        x: true,
        y: true,
        z: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [EventScripts] })
  @ApiNestedQuery(EventScriptsFindManyArgs)
  @GrpcMethod("EventScriptsService", "eventScriptsItems")
  async eventScriptsItems(
    @common.Req() request: Request
  ): Promise<EventScripts[]> {
    const args = plainToClass(EventScriptsFindManyArgs, request.query);
    return this.service.eventScriptsItems({
      ...args,
      select: {
        command: true,
        comment: true,
        createdAt: true,
        dataint: true,
        datalong: true,
        datalong2: true,
        delay: true,
        id: true,
        o: true,
        updatedAt: true,
        x: true,
        y: true,
        z: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: EventScripts })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @GrpcMethod("EventScriptsService", "eventScripts")
  async eventScripts(
    @common.Param() params: EventScriptsWhereUniqueInput
  ): Promise<EventScripts | null> {
    const result = await this.service.eventScripts({
      where: params,
      select: {
        command: true,
        comment: true,
        createdAt: true,
        dataint: true,
        datalong: true,
        datalong2: true,
        delay: true,
        id: true,
        o: true,
        updatedAt: true,
        x: true,
        y: true,
        z: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: EventScripts })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @GrpcMethod("EventScriptsService", "updateEventScripts")
  async updateEventScripts(
    @common.Param() params: EventScriptsWhereUniqueInput,
    @common.Body() data: EventScriptsUpdateInput
  ): Promise<EventScripts | null> {
    try {
      return await this.service.updateEventScripts({
        where: params,
        data: data,
        select: {
          command: true,
          comment: true,
          createdAt: true,
          dataint: true,
          datalong: true,
          datalong2: true,
          delay: true,
          id: true,
          o: true,
          updatedAt: true,
          x: true,
          y: true,
          z: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: EventScripts })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @GrpcMethod("EventScriptsService", "deleteEventScripts")
  async deleteEventScripts(
    @common.Param() params: EventScriptsWhereUniqueInput
  ): Promise<EventScripts | null> {
    try {
      return await this.service.deleteEventScripts({
        where: params,
        select: {
          command: true,
          comment: true,
          createdAt: true,
          dataint: true,
          datalong: true,
          datalong2: true,
          delay: true,
          id: true,
          o: true,
          updatedAt: true,
          x: true,
          y: true,
          z: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
