import { FloatNullableFilter } from "../../util/FloatNullableFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { DateTimeNullableFilter } from "../../util/DateTimeNullableFilter";
import { StringFilter } from "../../util/StringFilter";
import { IntNullableFilter } from "../../util/IntNullableFilter";

export type TbClreDedPdlsWhereInput = {
  aditTxQty?: FloatNullableFilter;
  aditTxQtyUtCd?: StringNullableFilter;
  apcAtpmEndDt?: StringNullableFilter;
  apcAtpmStrtDt?: StringNullableFilter;
  apcCd?: StringNullableFilter;
  bfDtlDcshDt?: StringNullableFilter;
  bfDtlDcshNo?: StringNullableFilter;
  bfPdlsNo?: StringNullableFilter;
  brndNm?: StringNullableFilter;
  cmdtClsfSpelCd?: StringNullableFilter;
  delYn?: StringNullableFilter;
  divdFfmnTpCd?: StringNullableFilter;
  dlngPdlsNm?: StringNullableFilter;
  frstRegstId?: StringNullableFilter;
  frstRgsrDttm?: DateTimeNullableFilter;
  hsCd?: StringNullableFilter;
  hsErrPvntVal?: StringNullableFilter;
  hsExcpMtrCd?: StringNullableFilter;
  id?: StringFilter;
  lastChgDttm?: DateTimeNullableFilter;
  lastChprId?: StringNullableFilter;
  mdfyDgcnt?: IntNullableFilter;
  mgDscnApreNo?: StringNullableFilter;
  nwprScarCmdtCd?: StringNullableFilter;
  oilTankNo?: StringNullableFilter;
  orcyCntyCd?: StringNullableFilter;
  pckgDesc?: StringNullableFilter;
  pckgShmrMarkNo?: StringNullableFilter;
  pdlsClsfBfhnJdgnPn?: StringNullableFilter;
  pdlsNm?: StringNullableFilter;
  pdlsNo?: StringNullableFilter;
  pdlsNtwg?: FloatNullableFilter;
  pdlsPckgGcnt?: IntNullableFilter;
  pdlsPckgUtCd?: StringNullableFilter;
  pdlsTtwg?: FloatNullableFilter;
  prcDtrmMeanCd?: StringNullableFilter;
  prhbCmdtCd?: StringNullableFilter;
  prvlCd?: StringNullableFilter;
  psmgtFfmnXpirPrid?: IntNullableFilter;
  qtaApreNo?: StringNullableFilter;
  qty?: FloatNullableFilter;
  qtyUtCd?: StringNullableFilter;
  reffNo?: StringNullableFilter;
  regmRqstCd?: StringNullableFilter;
  trifBaseVal?: StringNullableFilter;
  uprPdlsNo?: StringNullableFilter;
  vhclYn?: StringNullableFilter;
};
