export type TbClreDedPdls = {
  aditTxQty: number | null;
  aditTxQtyUtCd: string | null;
  apcAtpmEndDt: string | null;
  apcAtpmStrtDt: string | null;
  apcCd: string | null;
  bfDtlDcshDt: string | null;
  bfDtlDcshNo: string | null;
  bfPdlsNo: string | null;
  brndNm: string | null;
  cmdtClsfSpelCd: string | null;
  createdAt: Date;
  delYn: string | null;
  divdFfmnTpCd: string | null;
  dlngPdlsNm: string | null;
  frstRegstId: string | null;
  frstRgsrDttm: Date | null;
  hsCd: string | null;
  hsErrPvntVal: string | null;
  hsExcpMtrCd: string | null;
  id: string;
  lastChgDttm: Date | null;
  lastChprId: string | null;
  mdfyDgcnt: number | null;
  mgDscnApreNo: string | null;
  nwprScarCmdtCd: string | null;
  oilTankNo: string | null;
  orcyCntyCd: string | null;
  pckgDesc: string | null;
  pckgShmrMarkNo: string | null;
  pdlsClsfBfhnJdgnPn: string | null;
  pdlsNm: string | null;
  pdlsNo: string | null;
  pdlsNtwg: number | null;
  pdlsPckgGcnt: number | null;
  pdlsPckgUtCd: string | null;
  pdlsTtwg: number | null;
  prcDtrmMeanCd: string | null;
  prhbCmdtCd: string | null;
  prvlCd: string | null;
  psmgtFfmnXpirPrid: number | null;
  qtaApreNo: string | null;
  qty: number | null;
  qtyUtCd: string | null;
  reffNo: string | null;
  regmRqstCd: string | null;
  trifBaseVal: string | null;
  updatedAt: Date;
  uprPdlsNo: string | null;
  vhclYn: string | null;
};
