export type SerialNo = {
  amcExpiryDate: Date | null;
  asset: string | null;
  assetStatus: string | null;
  batchNo: string | null;
  brand: string | null;
  company: string | null;
  createdAt: Date;
  creation: Date | null;
  description: string | null;
  docstatus: number | null;
  employee: string | null;
  id: string;
  idx: number | null;
  itemCode: string | null;
  itemGroup: string | null;
  itemName: string | null;
  location: string | null;
  maintenanceStatus: string | null;
  modified: Date | null;
  modifiedBy: string | null;
  name: string | null;
  owner: string | null;
  purchaseDocumentNo: string | null;
  purchaseRate: number | null;
  serialNo: string | null;
  status: string | null;
  updatedAt: Date;
  warehouse: string | null;
  warrantyExpiryDate: Date | null;
  warrantyPeriod: number | null;
  workOrder: string | null;
};
