import { StringNullableFilter } from "../../util/StringNullableFilter";
import { FloatNullableFilter } from "../../util/FloatNullableFilter";
import { DateTimeNullableFilter } from "../../util/DateTimeNullableFilter";
import { IntNullableFilter } from "../../util/IntNullableFilter";
import { StringFilter } from "../../util/StringFilter";

export type PickListItemWhereInput = {
  batchNo?: StringNullableFilter;
  conversionFactor?: FloatNullableFilter;
  creation?: DateTimeNullableFilter;
  description?: StringNullableFilter;
  docstatus?: IntNullableFilter;
  id?: StringFilter;
  idx?: IntNullableFilter;
  itemCode?: StringNullableFilter;
  itemGroup?: StringNullableFilter;
  itemName?: StringNullableFilter;
  materialRequest?: StringNullableFilter;
  materialRequestItem?: StringNullableFilter;
  modified?: DateTimeNullableFilter;
  modifiedBy?: StringNullableFilter;
  name?: StringNullableFilter;
  owner?: StringNullableFilter;
  parent?: StringNullableFilter;
  parentfield?: StringNullableFilter;
  parenttype?: StringNullableFilter;
  pickedQty?: FloatNullableFilter;
  productBundleItem?: StringNullableFilter;
  qty?: FloatNullableFilter;
  salesOrder?: StringNullableFilter;
  salesOrderItem?: StringNullableFilter;
  serialAndBatchBundle?: StringNullableFilter;
  serialNo?: StringNullableFilter;
  stockQty?: FloatNullableFilter;
  stockReservedQty?: FloatNullableFilter;
  stockUom?: StringNullableFilter;
  uom?: StringNullableFilter;
  useSerialBatchFields?: IntNullableFilter;
  warehouse?: StringNullableFilter;
};
