import { IntNullableFilter } from "../../util/IntNullableFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { DateTimeNullableFilter } from "../../util/DateTimeNullableFilter";
import { BooleanNullableFilter } from "../../util/BooleanNullableFilter";
import { StringFilter } from "../../util/StringFilter";

export type EmailDigestWhereInput = {
  addQuote?: IntNullableFilter;
  bankBalance?: IntNullableFilter;
  calendarEvents?: IntNullableFilter;
  company?: StringNullableFilter;
  creation?: DateTimeNullableFilter;
  creditBalance?: IntNullableFilter;
  docstatus?: IntNullableFilter;
  enabled?: BooleanNullableFilter;
  expenseYearToDate?: IntNullableFilter;
  expensesBooked?: IntNullableFilter;
  frequency?: StringNullableFilter;
  id?: StringFilter;
  idx?: IntNullableFilter;
  income?: IntNullableFilter;
  incomeYearToDate?: IntNullableFilter;
  invoicedAmount?: IntNullableFilter;
  issue?: IntNullableFilter;
  modified?: DateTimeNullableFilter;
  modifiedBy?: StringNullableFilter;
  name?: StringNullableFilter;
  newQuotations?: IntNullableFilter;
  nextSend?: StringNullableFilter;
  notifications?: IntNullableFilter;
  owner?: StringNullableFilter;
  payables?: IntNullableFilter;
  pendingQuotations?: IntNullableFilter;
  project?: IntNullableFilter;
  purchaseInvoice?: IntNullableFilter;
  purchaseOrder?: IntNullableFilter;
  purchaseOrdersItemsOverdue?: IntNullableFilter;
  purchaseOrdersToBill?: IntNullableFilter;
  purchaseOrdersToReceive?: IntNullableFilter;
  salesInvoice?: IntNullableFilter;
  salesOrder?: IntNullableFilter;
  salesOrdersToBill?: IntNullableFilter;
  salesOrdersToDeliver?: IntNullableFilter;
  todoList?: IntNullableFilter;
};
