export type EmailDigest = {
  addQuote: number | null;
  bankBalance: number | null;
  calendarEvents: number | null;
  company: string | null;
  createdAt: Date;
  creation: Date | null;
  creditBalance: number | null;
  docstatus: number | null;
  enabled: boolean | null;
  expenseYearToDate: number | null;
  expensesBooked: number | null;
  frequency: string | null;
  id: string;
  idx: number | null;
  income: number | null;
  incomeYearToDate: number | null;
  invoicedAmount: number | null;
  issue: number | null;
  modified: Date | null;
  modifiedBy: string | null;
  name: string | null;
  newQuotations: number | null;
  nextSend: string | null;
  notifications: number | null;
  owner: string | null;
  payables: number | null;
  pendingQuotations: number | null;
  project: number | null;
  purchaseInvoice: number | null;
  purchaseOrder: number | null;
  purchaseOrdersItemsOverdue: number | null;
  purchaseOrdersToBill: number | null;
  purchaseOrdersToReceive: number | null;
  salesInvoice: number | null;
  salesOrder: number | null;
  salesOrdersToBill: number | null;
  salesOrdersToDeliver: number | null;
  todoList: number | null;
  updatedAt: Date;
};
