export type LandedCostPurchaseReceipt = {
  createdAt: Date;
  creation: Date | null;
  docstatus: number | null;
  grandTotal: number | null;
  id: string;
  idx: number | null;
  modified: Date | null;
  modifiedBy: string | null;
  name: string | null;
  owner: string | null;
  parent: string | null;
  parentfield: string | null;
  parenttype: string | null;
  postingDate: Date | null;
  receiptDocument: string | null;
  receiptDocumentType: string | null;
  supplier: string | null;
  updatedAt: Date;
};
