export type AssetValueAdjustmentCreateInput = {
  amendedFrom?: string | null;
  asset?: string | null;
  assetCategory?: string | null;
  company?: string | null;
  costCenter?: string | null;
  creation?: Date | null;
  currentAssetValue?: number | null;
  date?: Date | null;
  differenceAmount?: number | null;
  docstatus?: number | null;
  financeBook?: string | null;
  idx?: number | null;
  journalEntry?: string | null;
  modified?: Date | null;
  modifiedBy?: string | null;
  name?: string | null;
  newAssetValue?: number | null;
  owner?: string | null;
};
