export type EmployeeInternalWorkHistory = {
  branch: string | null;
  createdAt: Date;
  creation: Date | null;
  department: string | null;
  designation: string | null;
  docstatus: number | null;
  fromDate: Date | null;
  id: string;
  idx: number | null;
  modified: Date | null;
  modifiedBy: string | null;
  name: string | null;
  owner: string | null;
  parent: string | null;
  parentfield: string | null;
  parenttype: string | null;
  toDate: Date | null;
  updatedAt: Date;
};
