export type BomExplosionItemCreateInput = {
  amount?: number | null;
  creation?: Date | null;
  description?: string | null;
  docstatus?: number | null;
  idx?: number | null;
  image?: string | null;
  includeItemInManufacturing?: boolean | null;
  itemCode?: string | null;
  itemName?: string | null;
  modified?: Date | null;
  modifiedBy?: string | null;
  name?: string | null;
  operation?: string | null;
  owner?: string | null;
  parent?: string | null;
  parentfield?: string | null;
  parenttype?: string | null;
  qtyConsumedPerUnit?: number | null;
  rate?: number | null;
  sourceWarehouse?: string | null;
  sourcedBySupplier?: boolean | null;
  stockQty?: number | null;
  stockUom?: string | null;
};
