export type BomExplosionItem = {
  amount: number | null;
  createdAt: Date;
  creation: Date | null;
  description: string | null;
  docstatus: number | null;
  id: string;
  idx: number | null;
  image: string | null;
  includeItemInManufacturing: boolean | null;
  itemCode: string | null;
  itemName: string | null;
  modified: Date | null;
  modifiedBy: string | null;
  name: string | null;
  operation: string | null;
  owner: string | null;
  parent: string | null;
  parentfield: string | null;
  parenttype: string | null;
  qtyConsumedPerUnit: number | null;
  rate: number | null;
  sourceWarehouse: string | null;
  sourcedBySupplier: boolean | null;
  stockQty: number | null;
  stockUom: string | null;
  updatedAt: Date;
};
