export type DashboardChart = {
  aggregateFunctionBasedOn: string | null;
  basedOn: string | null;
  chartName: string | null;
  chartType: string | null;
  color: string | null;
  createdAt: Date;
  creation: Date | null;
  customOptions: string | null;
  docstatus: number | null;
  documentType: string | null;
  dynamicFiltersJson: string | null;
  filtersJson: string | null;
  fromDate: Date | null;
  groupByBasedOn: string | null;
  groupByType: string | null;
  heatmapYear: string | null;
  id: string;
  idx: number | null;
  isPublic: number | null;
  isStandard: number | null;
  lastSyncedOn: Date | null;
  modified: Date | null;
  modifiedBy: string | null;
  moduleField: string | null;
  numberOfGroups: number | null;
  owner: string | null;
  parentDocumentType: string | null;
  reportName: string | null;
  source: string | null;
  timeInterval: string | null;
  timeseries: number | null;
  timespan: string | null;
  toDate: Date | null;
  typeField: string | null;
  updatedAt: Date;
  useReportChart: number | null;
  valueBasedOn: string | null;
  xField: string | null;
};
