import { SortOrder } from "../../util/SortOrder";

export type DashboardChartOrderByInput = {
  aggregateFunctionBasedOn?: SortOrder;
  basedOn?: SortOrder;
  chartName?: SortOrder;
  chartType?: SortOrder;
  color?: SortOrder;
  createdAt?: SortOrder;
  creation?: SortOrder;
  customOptions?: SortOrder;
  docstatus?: SortOrder;
  documentType?: SortOrder;
  dynamicFiltersJson?: SortOrder;
  filtersJson?: SortOrder;
  fromDate?: SortOrder;
  groupByBasedOn?: SortOrder;
  groupByType?: SortOrder;
  heatmapYear?: SortOrder;
  id?: SortOrder;
  idx?: SortOrder;
  isPublic?: SortOrder;
  isStandard?: SortOrder;
  lastSyncedOn?: SortOrder;
  modified?: SortOrder;
  modifiedBy?: SortOrder;
  moduleField?: SortOrder;
  numberOfGroups?: SortOrder;
  owner?: SortOrder;
  parentDocumentType?: SortOrder;
  reportName?: SortOrder;
  source?: SortOrder;
  timeInterval?: SortOrder;
  timeseries?: SortOrder;
  timespan?: SortOrder;
  toDate?: SortOrder;
  typeField?: SortOrder;
  updatedAt?: SortOrder;
  useReportChart?: SortOrder;
  valueBasedOn?: SortOrder;
  xField?: SortOrder;
};
