export type AssignmentRuleUpdateInput = {
  assignCondition?: string | null;
  closeCondition?: string | null;
  creation?: Date | null;
  description?: string | null;
  disabled?: number | null;
  docstatus?: number | null;
  documentType?: string | null;
  dueDateBasedOn?: string | null;
  fieldField?: string | null;
  idx?: number | null;
  lastUser?: string | null;
  modified?: Date | null;
  modifiedBy?: string | null;
  name?: string | null;
  owner?: string | null;
  priority?: number | null;
  rule?: string | null;
  unassignCondition?: string | null;
};
