export type DocTypeAction = {
  action: string | null;
  actionType: string | null;
  createdAt: Date;
  creation: Date | null;
  custom: number | null;
  docstatus: number | null;
  group: string | null;
  hidden: number | null;
  id: string;
  idx: number | null;
  label: string | null;
  modified: Date | null;
  modifiedBy: string | null;
  name: string | null;
  owner: string | null;
  parent: string | null;
  parentfield: string | null;
  parenttype: string | null;
  updatedAt: Date;
};
