export type BankAccount = {
  account: string | null;
  accountName: string | null;
  accountSubtype: string | null;
  accountType: string | null;
  bank: string | null;
  bankAccountNo: string | null;
  branchCode: string | null;
  company: string | null;
  createdAt: Date;
  creation: Date | null;
  disabled: number | null;
  docstatus: number | null;
  iban: string | null;
  id: string;
  idx: number | null;
  integrationId: string | null;
  isCompanyAccount: number | null;
  isDefault: number | null;
  lastIntegrationDate: Date | null;
  mask: string | null;
  modified: Date | null;
  modifiedBy: string | null;
  name: string | null;
  owner: string | null;
  party: string | null;
  partyType: string | null;
  updatedAt: Date;
};
