export type DocPerm = {
  amend: number | null;
  cancel: number | null;
  create: number | null;
  createdAt: Date;
  creation: Date | null;
  deleteField: number | null;
  docstatus: number | null;
  email: number | null;
  exportField: number | null;
  id: string;
  idx: number | null;
  ifOwner: number | null;
  importField: number | null;
  match: string | null;
  modified: Date | null;
  modifiedBy: string | null;
  name: string | null;
  owner: string | null;
  parent: string | null;
  parentfield: string | null;
  parenttype: string | null;
  permlevel: number | null;
  print: number | null;
  read: number | null;
  report: number | null;
  role: string | null;
  select: number | null;
  share: number | null;
  submit: number | null;
  updatedAt: Date;
  write: number | null;
};
