export type AssetMaintenance = {
  assetCategory: string | null;
  assetName: string | null;
  company: string | null;
  createdAt: Date;
  creation: Date | null;
  docstatus: number | null;
  id: string;
  idx: number | null;
  itemCode: string | null;
  itemName: string | null;
  maintenanceManager: string | null;
  maintenanceManagerName: string | null;
  maintenanceTeam: string | null;
  modified: Date | null;
  modifiedBy: string | null;
  name: string | null;
  owner: string | null;
  updatedAt: Date;
};
