import { FloatNullableFilter } from "../../util/FloatNullableFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { DateTimeNullableFilter } from "../../util/DateTimeNullableFilter";
import { IntNullableFilter } from "../../util/IntNullableFilter";
import { StringFilter } from "../../util/StringFilter";

export type ChequePrintTemplateWhereInput = {
  accNoDistFromLeftEdge?: FloatNullableFilter;
  accNoDistFromTopEdge?: FloatNullableFilter;
  accPayDistFromLeftEdge?: FloatNullableFilter;
  accPayDistFromTopEdge?: FloatNullableFilter;
  amtInFiguresFromLeftEdge?: FloatNullableFilter;
  amtInFiguresFromTopEdge?: FloatNullableFilter;
  amtInWordWidth?: FloatNullableFilter;
  amtInWordsFromLeftEdge?: FloatNullableFilter;
  amtInWordsFromTopEdge?: FloatNullableFilter;
  amtInWordsLineSpacing?: FloatNullableFilter;
  bankName?: StringNullableFilter;
  chequeHeight?: FloatNullableFilter;
  chequeSize?: StringNullableFilter;
  chequeWidth?: FloatNullableFilter;
  creation?: DateTimeNullableFilter;
  dateDistFromLeftEdge?: FloatNullableFilter;
  dateDistFromTopEdge?: FloatNullableFilter;
  docstatus?: IntNullableFilter;
  hasPrintFormat?: IntNullableFilter;
  id?: StringFilter;
  idx?: IntNullableFilter;
  isAccountPayable?: IntNullableFilter;
  messageToShow?: StringNullableFilter;
  modified?: DateTimeNullableFilter;
  modifiedBy?: StringNullableFilter;
  owner?: StringNullableFilter;
  payerNameFromLeftEdge?: FloatNullableFilter;
  payerNameFromTopEdge?: FloatNullableFilter;
  scannedCheque?: StringNullableFilter;
  signatoryFromLeftEdge?: FloatNullableFilter;
  signatoryFromTopEdge?: FloatNullableFilter;
  startingPositionFromTopEdge?: FloatNullableFilter;
};
