export type CargoDeclarationContainer = {
  cagMgmtNo: string | null;
  cntrNo: string | null;
  cntrSrno: number | null;
  cntrTpCd: string | null;
  createdAt: Date;
  delYn: string | null;
  ecntrWght: number | null;
  frstRegstId: string | null;
  frstRgsrDttm: Date | null;
  id: string;
  lastChgDttm: Date | null;
  lastChprId: string | null;
  mrn: string | null;
  pckgGcnt: number | null;
  pckgUtCd: string | null;
  sealChpn1: string | null;
  sealChpn2: string | null;
  sealChpn3: string | null;
  sealNo1: string | null;
  sealNo2: string | null;
  sealNo3: string | null;
  ttwg: number | null;
  updatedAt: Date;
};
