import { SortOrder } from "../../util/SortOrder";

export type CreatureOrderByInput = {
  areaId?: SortOrder;
  createdAt?: SortOrder;
  curhealth?: SortOrder;
  curmana?: SortOrder;
  currentwaypoint?: SortOrder;
  equipmentId?: SortOrder;
  guid?: SortOrder;
  id?: SortOrder;
  map?: SortOrder;
  modelid?: SortOrder;
  movementType?: SortOrder;
  npcflag?: SortOrder;
  orientation?: SortOrder;
  phaseGroup?: SortOrder;
  phaseId?: SortOrder;
  phaseUseFlags?: SortOrder;
  positionX?: SortOrder;
  positionY?: SortOrder;
  positionZ?: SortOrder;
  scriptName?: SortOrder;
  spawnDifficulties?: SortOrder;
  spawntimesecs?: SortOrder;
  stringId?: SortOrder;
  terrainSwapMap?: SortOrder;
  unitFlags?: SortOrder;
  unitFlags2?: SortOrder;
  unitFlags3?: SortOrder;
  updatedAt?: SortOrder;
  verifiedBuild?: SortOrder;
  wanderDistance?: SortOrder;
  zoneId?: SortOrder;
};
