export type SalesPartnerUpdateInput = {
  commissionRate?: number | null;
  creation?: Date | null;
  description?: string | null;
  docstatus?: number | null;
  idx?: number | null;
  introduction?: string | null;
  logo?: string | null;
  modified?: Date | null;
  modifiedBy?: string | null;
  name?: string | null;
  owner?: string | null;
  partnerName?: string | null;
  partnerType?: string | null;
  partnerWebsite?: string | null;
  referralCode?: string | null;
  route?: string | null;
  showInWebsite?: number | null;
  territory?: string | null;
};
