export type CashierClosing = {
  amendedFrom: string | null;
  createdAt: Date;
  creation: Date | null;
  custody: number | null;
  date: Date | null;
  docstatus: number | null;
  expense: number | null;
  fromTime: Date | null;
  id: string;
  idx: number | null;
  modified: Date | null;
  modifiedBy: string | null;
  namingSeries: string | null;
  netAmount: number | null;
  outstandingAmount: number | null;
  owner: string | null;
  returns: number | null;
  time: Date | null;
  updatedAt: Date;
  user: string | null;
};
