export type BankClearanceDetailUpdateInput = {
  againstAccount?: string | null;
  amount?: string | null;
  chequeDate?: Date | null;
  chequeNumber?: string | null;
  clearanceDate?: Date | null;
  creation?: Date | null;
  docstatus?: number | null;
  idx?: number | null;
  modified?: Date | null;
  modifiedBy?: string | null;
  name?: string | null;
  owner?: string | null;
  parent?: string | null;
  parentfield?: string | null;
  parenttype?: string | null;
  paymentDocument?: string | null;
  paymentEntry?: string | null;
  postingDate?: Date | null;
};
