export type BankClearanceDetail = {
  againstAccount: string | null;
  amount: string | null;
  chequeDate: Date | null;
  chequeNumber: string | null;
  clearanceDate: Date | null;
  createdAt: Date;
  creation: Date | null;
  docstatus: number | null;
  id: string;
  idx: number | null;
  modified: Date | null;
  modifiedBy: string | null;
  name: string | null;
  owner: string | null;
  parent: string | null;
  parentfield: string | null;
  parenttype: string | null;
  paymentDocument: string | null;
  paymentEntry: string | null;
  postingDate: Date | null;
  updatedAt: Date;
};
