export type DeliveryTripUpdateInput = {
  amendedFrom?: string | null;
  company?: string | null;
  departureTime?: Date | null;
  docstatus?: number | null;
  driver?: string | null;
  driverAddress?: string | null;
  driverEmail?: string | null;
  driverName?: string | null;
  emailNotificationSent?: boolean | null;
  employee?: string | null;
  idx?: number | null;
  name?: string | null;
  namingSeries?: string | null;
  owner?: string | null;
  status?: string | null;
  totalDistance?: number | null;
  uom?: string | null;
  vehicle?: string | null;
};
