export type UnreconcilePaymentEntries = {
  account: string | null;
  accountCurrency: string | null;
  allocatedAmount: number | null;
  createdAt: Date;
  creation: Date | null;
  docstatus: number | null;
  id: string;
  idx: number | null;
  modified: Date | null;
  modifiedBy: string | null;
  name: string | null;
  owner: string | null;
  parent: string | null;
  parentfield: string | null;
  parenttype: string | null;
  party: string | null;
  partyType: string | null;
  referenceDoctype: string | null;
  referenceName: string | null;
  unlinked: number | null;
  updatedAt: Date;
};
