/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { CreatureTemplateSpell } from "./CreatureTemplateSpell";
import { CreatureTemplateSpellCountArgs } from "./CreatureTemplateSpellCountArgs";
import { CreatureTemplateSpellFindManyArgs } from "./CreatureTemplateSpellFindManyArgs";
import { CreatureTemplateSpellFindUniqueArgs } from "./CreatureTemplateSpellFindUniqueArgs";
import { DeleteCreatureTemplateSpellArgs } from "./DeleteCreatureTemplateSpellArgs";
import { CreatureTemplateSpellService } from "../creatureTemplateSpell.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => CreatureTemplateSpell)
export class CreatureTemplateSpellResolverBase {
  constructor(
    protected readonly service: CreatureTemplateSpellService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "CreatureTemplateSpell",
    action: "read",
    possession: "any",
  })
  async _creatureTemplateSpellsMeta(
    @graphql.Args() args: CreatureTemplateSpellCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [CreatureTemplateSpell])
  @nestAccessControl.UseRoles({
    resource: "CreatureTemplateSpell",
    action: "read",
    possession: "any",
  })
  async creatureTemplateSpells(
    @graphql.Args() args: CreatureTemplateSpellFindManyArgs
  ): Promise<CreatureTemplateSpell[]> {
    return this.service.creatureTemplateSpells(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => CreatureTemplateSpell, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "CreatureTemplateSpell",
    action: "read",
    possession: "own",
  })
  async creatureTemplateSpell(
    @graphql.Args() args: CreatureTemplateSpellFindUniqueArgs
  ): Promise<CreatureTemplateSpell | null> {
    const result = await this.service.creatureTemplateSpell(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => CreatureTemplateSpell)
  @nestAccessControl.UseRoles({
    resource: "CreatureTemplateSpell",
    action: "delete",
    possession: "any",
  })
  async deleteCreatureTemplateSpell(
    @graphql.Args() args: DeleteCreatureTemplateSpellArgs
  ): Promise<CreatureTemplateSpell | null> {
    try {
      return await this.service.deleteCreatureTemplateSpell(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
