export type ShipmentParcel = {
  count: number | null;
  createdAt: Date;
  creation: Date | null;
  docstatus: number | null;
  height: number | null;
  id: string;
  idx: number | null;
  length: number | null;
  modified: Date | null;
  modifiedBy: string | null;
  name: string | null;
  owner: string | null;
  parent: string | null;
  parentfield: string | null;
  parenttype: string | null;
  updatedAt: Date;
  weight: number | null;
  width: number | null;
};
