/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { CreatureTemplateModel } from "./CreatureTemplateModel";
import { CreatureTemplateModelCountArgs } from "./CreatureTemplateModelCountArgs";
import { CreatureTemplateModelFindManyArgs } from "./CreatureTemplateModelFindManyArgs";
import { CreatureTemplateModelFindUniqueArgs } from "./CreatureTemplateModelFindUniqueArgs";
import { DeleteCreatureTemplateModelArgs } from "./DeleteCreatureTemplateModelArgs";
import { CreatureTemplateModelService } from "../creatureTemplateModel.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => CreatureTemplateModel)
export class CreatureTemplateModelResolverBase {
  constructor(
    protected readonly service: CreatureTemplateModelService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "CreatureTemplateModel",
    action: "read",
    possession: "any",
  })
  async _creatureTemplateModelsMeta(
    @graphql.Args() args: CreatureTemplateModelCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [CreatureTemplateModel])
  @nestAccessControl.UseRoles({
    resource: "CreatureTemplateModel",
    action: "read",
    possession: "any",
  })
  async creatureTemplateModels(
    @graphql.Args() args: CreatureTemplateModelFindManyArgs
  ): Promise<CreatureTemplateModel[]> {
    return this.service.creatureTemplateModels(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => CreatureTemplateModel, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "CreatureTemplateModel",
    action: "read",
    possession: "own",
  })
  async creatureTemplateModel(
    @graphql.Args() args: CreatureTemplateModelFindUniqueArgs
  ): Promise<CreatureTemplateModel | null> {
    const result = await this.service.creatureTemplateModel(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => CreatureTemplateModel)
  @nestAccessControl.UseRoles({
    resource: "CreatureTemplateModel",
    action: "delete",
    possession: "any",
  })
  async deleteCreatureTemplateModel(
    @graphql.Args() args: DeleteCreatureTemplateModelArgs
  ): Promise<CreatureTemplateModel | null> {
    try {
      return await this.service.deleteCreatureTemplateModel(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
