export type BomOperationCreateInput = {
  baseCostPerUnit?: number | null;
  baseHourRate?: number | null;
  baseOperatingCost?: number | null;
  batchSize?: number | null;
  costPerUnit?: number | null;
  creation?: Date | null;
  description?: string | null;
  docstatus?: number | null;
  fixedTime?: boolean | null;
  hourRate?: number | null;
  idx?: number | null;
  image?: string | null;
  modified?: Date | null;
  modifiedBy?: string | null;
  name?: string | null;
  operatingCost?: number | null;
  operation?: string | null;
  owner?: string | null;
  parent?: string | null;
  parentfield?: string | null;
  parenttype?: string | null;
  sequenceId?: number | null;
  setCostBasedOnBomQty?: boolean | null;
  timeInMins?: number | null;
  workstation?: string | null;
  workstationType?: string | null;
};
