export type PurchaseInvoiceAdvanceCreateInput = {
  advanceAmount?: number | null;
  allocatedAmount?: number | null;
  creation?: Date | null;
  docstatus?: number | null;
  exchangeGainLoss?: number | null;
  idx?: number | null;
  modified?: Date | null;
  modifiedBy?: string | null;
  name?: string | null;
  owner?: string | null;
  parent?: string | null;
  parentField?: string | null;
  parentType?: string | null;
  refExchangeRate?: number | null;
  referenceName?: string | null;
  referenceRow?: string | null;
  referenceType?: string | null;
  remarks?: string | null;
};
