export type PurchaseInvoiceAdvance = {
  advanceAmount: number | null;
  allocatedAmount: number | null;
  createdAt: Date;
  creation: Date | null;
  docstatus: number | null;
  exchangeGainLoss: number | null;
  id: string;
  idx: number | null;
  modified: Date | null;
  modifiedBy: string | null;
  name: string | null;
  owner: string | null;
  parent: string | null;
  parentField: string | null;
  parentType: string | null;
  refExchangeRate: number | null;
  referenceName: string | null;
  referenceRow: string | null;
  referenceType: string | null;
  remarks: string | null;
  updatedAt: Date;
};
