import { FloatNullableFilter } from "../../util/FloatNullableFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { IntNullableFilter } from "../../util/IntNullableFilter";
import { DateTimeNullableFilter } from "../../util/DateTimeNullableFilter";
import { StringFilter } from "../../util/StringFilter";

export type AssetWhereInput = {
  additionalAssetCost?: FloatNullableFilter;
  amendedFrom?: StringNullableFilter;
  assetCategory?: StringNullableFilter;
  assetName?: StringNullableFilter;
  assetOwner?: StringNullableFilter;
  assetOwnerCompany?: StringNullableFilter;
  assetQuantity?: IntNullableFilter;
  availableForUseDate?: DateTimeNullableFilter;
  bookedFixedAsset?: IntNullableFilter;
  calculateDepreciation?: IntNullableFilter;
  company?: StringNullableFilter;
  comprehensiveInsurance?: StringNullableFilter;
  costCenter?: StringNullableFilter;
  creation?: DateTimeNullableFilter;
  custodian?: StringNullableFilter;
  customer?: StringNullableFilter;
  defaultFinanceBook?: StringNullableFilter;
  department?: StringNullableFilter;
  deprEntryPostingStatus?: StringNullableFilter;
  depreciationMethod?: StringNullableFilter;
  disposalDate?: DateTimeNullableFilter;
  docstatus?: IntNullableFilter;
  frequencyOfDepreciation?: IntNullableFilter;
  grossPurchaseAmount?: FloatNullableFilter;
  id?: StringFilter;
  idx?: IntNullableFilter;
  image?: StringNullableFilter;
  insuranceEndDate?: DateTimeNullableFilter;
  insuranceStartDate?: DateTimeNullableFilter;
  insuredValue?: StringNullableFilter;
  insurer?: StringNullableFilter;
  isCompositeAsset?: IntNullableFilter;
  isExistingAsset?: IntNullableFilter;
  isFullyDepreciated?: IntNullableFilter;
  itemCode?: StringNullableFilter;
  itemName?: StringNullableFilter;
  journalEntryForScrap?: StringNullableFilter;
  location?: StringNullableFilter;
  maintenanceRequired?: IntNullableFilter;
  modified?: DateTimeNullableFilter;
  modifiedBy?: StringNullableFilter;
  name?: StringNullableFilter;
  namingSeries?: StringNullableFilter;
  nextDepreciationDate?: DateTimeNullableFilter;
  openingAccumulatedDepreciation?: FloatNullableFilter;
  openingNumberOfBookedDepreciations?: IntNullableFilter;
  owner?: StringNullableFilter;
  policyNumber?: StringNullableFilter;
  purchaseAmount?: FloatNullableFilter;
  purchaseDate?: DateTimeNullableFilter;
  purchaseInvoice?: StringNullableFilter;
  purchaseInvoiceItem?: StringNullableFilter;
  purchaseReceipt?: StringNullableFilter;
  purchaseReceiptItem?: StringNullableFilter;
  splitFrom?: StringNullableFilter;
  status?: StringNullableFilter;
  supplier?: StringNullableFilter;
  totalAssetCost?: FloatNullableFilter;
  totalNumberOfDepreciations?: IntNullableFilter;
  valueAfterDepreciation?: FloatNullableFilter;
};
