import { FloatNullableFilter } from "../../util/FloatNullableFilter";
import { IntNullableFilter } from "../../util/IntNullableFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { DateTimeNullableFilter } from "../../util/DateTimeNullableFilter";
import { StringFilter } from "../../util/StringFilter";

export type PosInvoiceItemWhereInput = {
  actualBatchQty?: FloatNullableFilter;
  actualQty?: FloatNullableFilter;
  allowZeroValuationRate?: IntNullableFilter;
  amount?: FloatNullableFilter;
  asset?: StringNullableFilter;
  barcode?: StringNullableFilter;
  baseAmount?: FloatNullableFilter;
  baseNetAmount?: FloatNullableFilter;
  baseNetRate?: FloatNullableFilter;
  basePriceListRate?: FloatNullableFilter;
  baseRate?: FloatNullableFilter;
  baseRateWithMargin?: FloatNullableFilter;
  batchNo?: StringNullableFilter;
  brand?: StringNullableFilter;
  conversionFactor?: FloatNullableFilter;
  costCenter?: StringNullableFilter;
  creation?: DateTimeNullableFilter;
  customerItemCode?: StringNullableFilter;
  deferredRevenueAccount?: StringNullableFilter;
  deliveredBySupplier?: IntNullableFilter;
  deliveredQty?: FloatNullableFilter;
  deliveryNote?: StringNullableFilter;
  description?: StringNullableFilter;
  discountAmount?: FloatNullableFilter;
  discountPercentage?: FloatNullableFilter;
  dnDetail?: StringNullableFilter;
  docStatus?: IntNullableFilter;
  enableDeferredRevenue?: IntNullableFilter;
  expenseAccount?: StringNullableFilter;
  financeBook?: StringNullableFilter;
  grantCommission?: IntNullableFilter;
  hasItemScanned?: IntNullableFilter;
  id?: StringFilter;
  idx?: IntNullableFilter;
  image?: StringNullableFilter;
  incomeAccount?: StringNullableFilter;
  isFixedAsset?: IntNullableFilter;
  isFreeItem?: IntNullableFilter;
  itemCode?: StringNullableFilter;
  itemGroup?: StringNullableFilter;
  itemName?: StringNullableFilter;
  itemTaxRate?: StringNullableFilter;
  itemTaxTemplate?: StringNullableFilter;
  marginRateOrAmount?: FloatNullableFilter;
  marginType?: StringNullableFilter;
  modified?: DateTimeNullableFilter;
  modifiedBy?: StringNullableFilter;
  name?: StringNullableFilter;
  netAmount?: FloatNullableFilter;
  netRate?: FloatNullableFilter;
  owner?: StringNullableFilter;
  pageBreak?: IntNullableFilter;
  parent?: StringNullableFilter;
  parentField?: StringNullableFilter;
  parentType?: StringNullableFilter;
  posInvoiceItem?: StringNullableFilter;
  priceListRate?: FloatNullableFilter;
  pricingRules?: StringNullableFilter;
  project?: StringNullableFilter;
  qty?: FloatNullableFilter;
  qualityInspection?: StringNullableFilter;
  rate?: FloatNullableFilter;
  rateWithMargin?: FloatNullableFilter;
  salesOrder?: StringNullableFilter;
  serialAndBatchBundle?: StringNullableFilter;
  serialNo?: StringNullableFilter;
  serviceEndDate?: DateTimeNullableFilter;
  serviceStartDate?: DateTimeNullableFilter;
  serviceStopDate?: DateTimeNullableFilter;
  soDetail?: StringNullableFilter;
  stockQty?: FloatNullableFilter;
  stockUom?: StringNullableFilter;
  targetWarehouse?: StringNullableFilter;
  totalWeight?: FloatNullableFilter;
  uom?: StringNullableFilter;
  useSerialBatchFields?: IntNullableFilter;
  warehouse?: StringNullableFilter;
  weightPerUnit?: FloatNullableFilter;
  weightUom?: StringNullableFilter;
};
