import { BooleanNullableFilter } from "../../util/BooleanNullableFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { IntNullableFilter } from "../../util/IntNullableFilter";
import { DateTimeNullableFilter } from "../../util/DateTimeNullableFilter";
import { StringFilter } from "../../util/StringFilter";
import { JsonFilter } from "../../util/JsonFilter";

export type CustomizeFormFieldWhereInput = {
  allowBulkEdit?: BooleanNullableFilter;
  allowInQuickEntry?: BooleanNullableFilter;
  allowOnSubmit?: BooleanNullableFilter;
  bold?: BooleanNullableFilter;
  collapsible?: BooleanNullableFilter;
  collapsibleDependsOn?: StringNullableFilter;
  columns?: IntNullableFilter;
  creation?: DateTimeNullableFilter;
  defaultField?: StringNullableFilter;
  dependsOn?: StringNullableFilter;
  description?: StringNullableFilter;
  docstatus?: IntNullableFilter;
  fetchFrom?: StringNullableFilter;
  fetchIfEmpty?: BooleanNullableFilter;
  fieldname?: StringNullableFilter;
  fieldtype?: StringNullableFilter;
  hidden?: BooleanNullableFilter;
  hideBorder?: BooleanNullableFilter;
  hideDays?: BooleanNullableFilter;
  hideSeconds?: BooleanNullableFilter;
  id?: StringFilter;
  idx?: IntNullableFilter;
  ignoreUserPermissions?: BooleanNullableFilter;
  ignoreXssFilter?: BooleanNullableFilter;
  inFilter?: BooleanNullableFilter;
  inGlobalSearch?: BooleanNullableFilter;
  inListView?: BooleanNullableFilter;
  inPreview?: BooleanNullableFilter;
  inStandardFilter?: BooleanNullableFilter;
  isCustomField?: BooleanNullableFilter;
  isSystemGenerated?: BooleanNullableFilter;
  isVirtual?: BooleanNullableFilter;
  label?: StringNullableFilter;
  length?: IntNullableFilter;
  linkFilters?: JsonFilter;
  mandatoryDependsOn?: StringNullableFilter;
  modified?: DateTimeNullableFilter;
  modifiedBy?: StringNullableFilter;
  name?: StringNullableFilter;
  noCopy?: BooleanNullableFilter;
  nonNegative?: BooleanNullableFilter;
  options?: StringNullableFilter;
  owner?: StringNullableFilter;
  parent?: StringNullableFilter;
  parentfield?: StringNullableFilter;
  parenttype?: StringNullableFilter;
  permlevel?: IntNullableFilter;
  precision?: StringNullableFilter;
  printHide?: BooleanNullableFilter;
  printHideIfNoValue?: BooleanNullableFilter;
  printWidth?: StringNullableFilter;
  readOnly?: BooleanNullableFilter;
  readOnlyDependsOn?: StringNullableFilter;
  rememberLastSelectedValue?: BooleanNullableFilter;
  reportHide?: BooleanNullableFilter;
  reqd?: BooleanNullableFilter;
  showDashboard?: BooleanNullableFilter;
  sortOptions?: BooleanNullableFilter;
  translatable?: BooleanNullableFilter;
  unique?: BooleanNullableFilter;
  width?: StringNullableFilter;
};
