import { StringNullableFilter } from "../../util/StringNullableFilter";
import { DateTimeNullableFilter } from "../../util/DateTimeNullableFilter";
import { IntNullableFilter } from "../../util/IntNullableFilter";
import { StringFilter } from "../../util/StringFilter";
import { FloatNullableFilter } from "../../util/FloatNullableFilter";

export type ShipmentWhereInput = {
  amendedFrom?: StringNullableFilter;
  awbNumber?: StringNullableFilter;
  carrier?: StringNullableFilter;
  carrierService?: StringNullableFilter;
  creation?: DateTimeNullableFilter;
  deliveryAddress?: StringNullableFilter;
  deliveryAddressName?: StringNullableFilter;
  deliveryCompany?: StringNullableFilter;
  deliveryContact?: StringNullableFilter;
  deliveryContactEmail?: StringNullableFilter;
  deliveryContactName?: StringNullableFilter;
  deliveryCustomer?: StringNullableFilter;
  deliverySupplier?: StringNullableFilter;
  deliveryTo?: StringNullableFilter;
  deliveryToType?: StringNullableFilter;
  descriptionOfContent?: StringNullableFilter;
  docstatus?: IntNullableFilter;
  id?: StringFilter;
  idx?: IntNullableFilter;
  incoterm?: StringNullableFilter;
  likedBy?: StringNullableFilter;
  modified?: DateTimeNullableFilter;
  modifiedBy?: StringNullableFilter;
  name?: StringNullableFilter;
  owner?: StringNullableFilter;
  pallets?: StringNullableFilter;
  parcelTemplate?: StringNullableFilter;
  pickup?: StringNullableFilter;
  pickupAddress?: StringNullableFilter;
  pickupAddressName?: StringNullableFilter;
  pickupCompany?: StringNullableFilter;
  pickupContact?: StringNullableFilter;
  pickupContactEmail?: StringNullableFilter;
  pickupContactName?: StringNullableFilter;
  pickupContactPerson?: StringNullableFilter;
  pickupCustomer?: StringNullableFilter;
  pickupDate?: DateTimeNullableFilter;
  pickupFrom?: DateTimeNullableFilter;
  pickupFromType?: StringNullableFilter;
  pickupSupplier?: StringNullableFilter;
  pickupTo?: DateTimeNullableFilter;
  pickupType?: StringNullableFilter;
  serviceProvider?: StringNullableFilter;
  shipmentAmount?: FloatNullableFilter;
  shipmentId?: StringNullableFilter;
  shipmentType?: StringNullableFilter;
  status?: StringNullableFilter;
  trackingStatus?: StringNullableFilter;
  trackingStatusInfo?: StringNullableFilter;
  trackingUrl?: StringNullableFilter;
  valueOfGoods?: FloatNullableFilter;
};
