import { QuestObjectiveCreateNestedManyWithoutQuestObjectiveCompletionEffectsInput } from "./QuestObjectiveCreateNestedManyWithoutQuestObjectiveCompletionEffectsInput";

export type QuestObjectiveCompletionEffectCreateInput = {
  questObjectives?: QuestObjectiveCreateNestedManyWithoutQuestObjectiveCompletionEffectsInput;
};
