export type ItemPrice = {
  batchNo: string | null;
  brand: string | null;
  buying: boolean | null;
  createdAt: Date;
  currency: string | null;
  customer: string | null;
  docstatus: number | null;
  id: string;
  idx: number | null;
  itemCode: string | null;
  itemDescription: string | null;
  itemName: string | null;
  leadTimeDays: number | null;
  modifiedBy: string | null;
  name: string | null;
  note: string | null;
  owner: string | null;
  packingUnit: number | null;
  priceList: string | null;
  priceListRate: number | null;
  reference: string | null;
  selling: boolean | null;
  supplier: string | null;
  uom: string | null;
  updatedAt: Date;
  validFrom: Date | null;
  validUpto: Date | null;
};
