export type ItemPriceUpdateInput = {
  batchNo?: string | null;
  brand?: string | null;
  buying?: boolean | null;
  currency?: string | null;
  customer?: string | null;
  docstatus?: number | null;
  idx?: number | null;
  itemCode?: string | null;
  itemDescription?: string | null;
  itemName?: string | null;
  leadTimeDays?: number | null;
  modifiedBy?: string | null;
  name?: string | null;
  note?: string | null;
  owner?: string | null;
  packingUnit?: number | null;
  priceList?: string | null;
  priceListRate?: number | null;
  reference?: string | null;
  selling?: boolean | null;
  supplier?: string | null;
  uom?: string | null;
  validFrom?: Date | null;
  validUpto?: Date | null;
};
