export type Item = {
  allowAlternativeItem: number | null;
  autoCreateAssets: number | null;
  createdAt: Date;
  creation: Date | null;
  disabled: number | null;
  docstatus: number | null;
  hasVariants: number | null;
  id: string;
  idx: number | null;
  isFixedAsset: number | null;
  isGroupedAsset: number | null;
  isStockItem: number | null;
  itemCode: string | null;
  itemGroup: string | null;
  itemName: string | null;
  modified: Date | null;
  modifiedBy: string | null;
  name: string | null;
  namingSeries: string | null;
  openingStock: number | null;
  owner: string | null;
  standardRate: number | null;
  stockUom: string | null;
  updatedAt: Date;
  valuationRate: number | null;
};
