export type ClosingStockBalance = {
  amendedFrom: string | null;
  company: string | null;
  createdAt: Date;
  creation: Date | null;
  docstatus: number | null;
  fromDate: Date | null;
  id: string;
  idx: number | null;
  includeUom: string | null;
  itemCode: string | null;
  itemGroup: string | null;
  modified: Date | null;
  modifiedBy: string | null;
  namingSeries: string | null;
  owner: string | null;
  status: string | null;
  toDate: Date | null;
  updatedAt: Date;
  warehouse: string | null;
  warehouseType: string | null;
};
