export type Lead = {
  annualRevenue: number | null;
  blogSubscriber: number | null;
  campaignName: string | null;
  city: string | null;
  company: string | null;
  companyName: string | null;
  country: string | null;
  createdAt: Date;
  creation: Date | null;
  customer: string | null;
  disabled: number | null;
  docstatus: number | null;
  emailId: string | null;
  fax: string | null;
  firstName: string | null;
  gender: string | null;
  id: string;
  idx: number | null;
  image: string | null;
  industry: string | null;
  jobTitle: string | null;
  language: string | null;
  lastName: string | null;
  leadName: string | null;
  leadOwner: string | null;
  marketSegment: string | null;
  middleName: string | null;
  mobileNo: string | null;
  modified: Date | null;
  modifiedBy: string | null;
  name: string | null;
  namingSeries: string | null;
  noOfEmployees: string | null;
  owner: string | null;
  phone: string | null;
  phoneExt: string | null;
  qualificationStatus: string | null;
  qualifiedBy: string | null;
  qualifiedOn: Date | null;
  requestType: string | null;
  salutation: string | null;
  source: string | null;
  state: string | null;
  status: string | null;
  territory: string | null;
  title: string | null;
  typeField: string | null;
  unsubscribed: number | null;
  updatedAt: Date;
  website: string | null;
};
