export type PurchaseReceiptItemSupplied = {
  amount: number | null;
  batchNo: string | null;
  bomDetailNo: string | null;
  consumedQty: number | null;
  conversionFactor: number | null;
  createdAt: Date;
  creation: Date | null;
  currentStock: number | null;
  description: string | null;
  docstatus: number | null;
  id: string;
  idx: number | null;
  itemName: string | null;
  mainItemCode: string | null;
  modified: Date | null;
  modifiedBy: string | null;
  name: string | null;
  owner: string | null;
  parent: string | null;
  parentField: string | null;
  parentType: string | null;
  purchaseOrder: string | null;
  rate: number | null;
  referenceName: string | null;
  requiredQty: number | null;
  rmItemCode: string | null;
  serialNo: string | null;
  stockUom: string | null;
  updatedAt: Date;
};
