export type ProductionPlanSubAssemblyItem = {
  actualQty: number | null;
  bomLevel: number | null;
  bomNo: string | null;
  createdAt: Date;
  creation: Date | null;
  description: string | null;
  docstatus: number | null;
  fgWarehouse: string | null;
  id: string;
  idx: number | null;
  indent: number | null;
  itemName: string | null;
  modified: Date | null;
  modifiedBy: string | null;
  name: string | null;
  owner: string | null;
  parent: string | null;
  parentItemCode: string | null;
  parentfield: string | null;
  parenttype: string | null;
  productionItem: string | null;
  productionPlanItem: string | null;
  projectedQty: number | null;
  purchaseOrder: string | null;
  qty: number | null;
  receivedQty: number | null;
  scheduleDate: Date | null;
  stockUom: string | null;
  supplier: string | null;
  typeOfManufacturing: string | null;
  uom: string | null;
  updatedAt: Date;
  woProducedQty: number | null;
};
