import { FloatNullableFilter } from "../../util/FloatNullableFilter";
import { IntNullableFilter } from "../../util/IntNullableFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { DateTimeNullableFilter } from "../../util/DateTimeNullableFilter";
import { StringFilter } from "../../util/StringFilter";

export type ProductionPlanSubAssemblyItemWhereInput = {
  actualQty?: FloatNullableFilter;
  bomLevel?: IntNullableFilter;
  bomNo?: StringNullableFilter;
  creation?: DateTimeNullableFilter;
  description?: StringNullableFilter;
  docstatus?: IntNullableFilter;
  fgWarehouse?: StringNullableFilter;
  id?: StringFilter;
  idx?: IntNullableFilter;
  indent?: IntNullableFilter;
  itemName?: StringNullableFilter;
  modified?: DateTimeNullableFilter;
  modifiedBy?: StringNullableFilter;
  name?: StringNullableFilter;
  owner?: StringNullableFilter;
  parent?: StringNullableFilter;
  parentItemCode?: StringNullableFilter;
  parentfield?: StringNullableFilter;
  parenttype?: StringNullableFilter;
  productionItem?: StringNullableFilter;
  productionPlanItem?: StringNullableFilter;
  projectedQty?: FloatNullableFilter;
  purchaseOrder?: StringNullableFilter;
  qty?: FloatNullableFilter;
  receivedQty?: FloatNullableFilter;
  scheduleDate?: DateTimeNullableFilter;
  stockUom?: StringNullableFilter;
  supplier?: StringNullableFilter;
  typeOfManufacturing?: StringNullableFilter;
  uom?: StringNullableFilter;
  woProducedQty?: FloatNullableFilter;
};
