export type CostCenter = {
  company: string | null;
  costCenterName: string | null;
  costCenterNumber: string | null;
  createdAt: Date;
  creation: Date | null;
  disabled: boolean | null;
  docstatus: number | null;
  id: string;
  idx: number | null;
  isGroup: boolean | null;
  lft: number | null;
  modified: Date | null;
  modifiedBy: string | null;
  name: string | null;
  oldParent: string | null;
  owner: string | null;
  parentCostCenter: string | null;
  rgt: number | null;
  updatedAt: Date;
};
