export type StockReservationEntry = {
  amendedFrom: string | null;
  availableQty: number | null;
  company: string | null;
  createdAt: Date;
  creation: Date | null;
  deliveredQty: number | null;
  docstatus: number | null;
  fromVoucherDetailNo: string | null;
  fromVoucherNo: string | null;
  fromVoucherType: string | null;
  hasBatchNo: boolean | null;
  hasSerialNo: boolean | null;
  id: string;
  idx: number | null;
  itemCode: string | null;
  modified: Date | null;
  modifiedBy: string | null;
  name: string | null;
  owner: string | null;
  project: string | null;
  reservationBasedOn: string | null;
  reservedQty: number | null;
  status: string | null;
  stockUom: string | null;
  updatedAt: Date;
  voucherDetailNo: string | null;
  voucherNo: string | null;
  voucherQty: number | null;
  voucherType: string | null;
  warehouse: string | null;
};
