export type TbClreDedCoUpdateInput = {
  dcerAddr?: string | null;
  dcerCoNm?: string | null;
  delYn?: string | null;
  exppnAddr?: string | null;
  exppnCoNm?: string | null;
  exppnEml?: string | null;
  frstRegstId?: string | null;
  frstRgsrDttm?: Date | null;
  imppnAddr?: string | null;
  imppnCoNm?: string | null;
  lastChgDttm?: Date | null;
  lastChprId?: string | null;
  mdfyDgcnt?: number | null;
  reffNo?: string | null;
  txprAddr?: string | null;
  txprCoNm?: string | null;
  txprEml?: string | null;
  txprTlphNo?: string | null;
};
