export type EmployeeExternalWorkHistory = {
  address: string | null;
  companyName: string | null;
  contact: string | null;
  createdAt: Date;
  creation: Date | null;
  designation: string | null;
  docstatus: number | null;
  id: string;
  idx: number | null;
  modified: Date | null;
  modifiedBy: string | null;
  name: string | null;
  owner: string | null;
  parent: string | null;
  parentfield: string | null;
  parenttype: string | null;
  salary: number | null;
  totalExperience: string | null;
  updatedAt: Date;
};
