import { BooleanNullableFilter } from "../../util/BooleanNullableFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { FloatNullableFilter } from "../../util/FloatNullableFilter";
import { DateTimeNullableFilter } from "../../util/DateTimeNullableFilter";
import { IntNullableFilter } from "../../util/IntNullableFilter";
import { StringFilter } from "../../util/StringFilter";

export type BomWhereInput = {
  allowAlternativeItem?: BooleanNullableFilter;
  amendedFrom?: StringNullableFilter;
  baseOperatingCost?: FloatNullableFilter;
  baseRawMaterialCost?: FloatNullableFilter;
  baseScrapMaterialCost?: FloatNullableFilter;
  baseTotalCost?: FloatNullableFilter;
  bomCreator?: StringNullableFilter;
  bomCreatorItem?: StringNullableFilter;
  buyingPriceList?: StringNullableFilter;
  company?: StringNullableFilter;
  conversionRate?: FloatNullableFilter;
  creation?: DateTimeNullableFilter;
  currency?: StringNullableFilter;
  description?: StringNullableFilter;
  docstatus?: IntNullableFilter;
  fgBasedOperatingCost?: BooleanNullableFilter;
  hasVariants?: BooleanNullableFilter;
  id?: StringFilter;
  idx?: IntNullableFilter;
  image?: StringNullableFilter;
  inspectionRequired?: BooleanNullableFilter;
  isActive?: BooleanNullableFilter;
  isDefault?: BooleanNullableFilter;
  item?: StringNullableFilter;
  itemName?: StringNullableFilter;
  modified?: DateTimeNullableFilter;
  modifiedBy?: StringNullableFilter;
  name?: StringNullableFilter;
  operatingCost?: FloatNullableFilter;
  operatingCostPerBomQuantity?: FloatNullableFilter;
  owner?: StringNullableFilter;
  plcConversionRate?: FloatNullableFilter;
  priceListCurrency?: StringNullableFilter;
  processLossPercentage?: FloatNullableFilter;
  processLossQty?: FloatNullableFilter;
  project?: StringNullableFilter;
  qualityInspectionTemplate?: StringNullableFilter;
  quantity?: FloatNullableFilter;
  rawMaterialCost?: FloatNullableFilter;
  rmCostAsPer?: StringNullableFilter;
  route?: StringNullableFilter;
  routing?: StringNullableFilter;
  scrapMaterialCost?: FloatNullableFilter;
  setRateOfSubAssemblyItemBasedOnBom?: BooleanNullableFilter;
  showInWebsite?: BooleanNullableFilter;
  showItems?: BooleanNullableFilter;
  showOperations?: BooleanNullableFilter;
  thumbnail?: StringNullableFilter;
  totalCost?: FloatNullableFilter;
  transferMaterialAgainst?: StringNullableFilter;
  uom?: StringNullableFilter;
  webLongDescription?: StringNullableFilter;
  websiteImage?: StringNullableFilter;
  withOperations?: BooleanNullableFilter;
};
