export type EmployeeEducation = {
  classPer: string | null;
  createdAt: Date;
  creation: Date | null;
  docstatus: number | null;
  id: string;
  idx: number | null;
  level: string | null;
  majOptSubj: string | null;
  modified: Date | null;
  modifiedBy: string | null;
  name: string | null;
  owner: string | null;
  parent: string | null;
  parentfield: string | null;
  parenttype: string | null;
  qualification: string | null;
  schoolUniv: string | null;
  updatedAt: Date;
  yearOfPassing: number | null;
};
