export type SerialAndBatchEntry = {
  batchNo: string | null;
  createdAt: Date;
  creation: Date | null;
  deliveredQty: number | null;
  docstatus: number | null;
  id: string;
  idx: number | null;
  incomingRate: number | null;
  isOutward: number | null;
  modified: Date | null;
  modifiedBy: string | null;
  name: string | null;
  outgoingRate: number | null;
  owner: string | null;
  parent: string | null;
  parentfield: string | null;
  parenttype: string | null;
  qty: number | null;
  serialNo: string | null;
  stockQueue: string | null;
  stockValueDifference: number | null;
  updatedAt: Date;
  warehouse: string | null;
};
