export type Currency = {
  createdAt: Date;
  creation: Date | null;
  currencyName: string | null;
  docstatus: number | null;
  enabled: boolean | null;
  fraction: string | null;
  fractionUnits: number | null;
  id: string;
  idx: number | null;
  modified: Date | null;
  modifiedBy: string | null;
  name: string | null;
  numberFormat: string | null;
  owner: string | null;
  smallestCurrencyFractionValue: number | null;
  symbolField: string | null;
  symbolOnRight: boolean | null;
  updatedAt: Date;
};
