export type PaymentLedgerEntryUpdateInput = {
  account?: string | null;
  accountCurrency?: string | null;
  accountType?: string | null;
  againstVoucherNo?: string | null;
  againstVoucherType?: string | null;
  amount?: number | null;
  amountInAccountCurrency?: number | null;
  company?: string | null;
  costCenter?: string | null;
  creation?: Date | null;
  delinked?: number | null;
  docstatus?: number | null;
  dueDate?: Date | null;
  financeBook?: string | null;
  idx?: number | null;
  modified?: Date | null;
  modifiedBy?: string | null;
  name?: string | null;
  owner?: string | null;
  party?: string | null;
  partyType?: string | null;
  postingDate?: Date | null;
  remarks?: string | null;
  voucherDetailNo?: string | null;
  voucherNo?: string | null;
  voucherType?: string | null;
};
