export type CariCagDcshBlTrnp = {
  chssNo: string | null;
  createdAt: Date;
  delYn: string | null;
  drvrNm: string | null;
  drvrPsprNo: string | null;
  frstRegstId: string | null;
  frstRgsrDttm: Date | null;
  id: string;
  lastChgDttm: Date | null;
  lastChprId: string | null;
  mrn: string | null;
  trnpMethNatCd: string | null;
  updatedAt: Date;
  vhclMnurCd: string | null;
  vhclNttn: number | null;
  vhclPtCd: string | null;
  vhclRgsrNo: string | null;
  vhclSrno: number | null;
  vhclTtn: number | null;
};
