export type MaintenanceVisitPurpose = {
  createdAt: Date;
  creation: Date | null;
  description: string | null;
  docstatus: number | null;
  id: string;
  idx: number | null;
  itemCode: string | null;
  itemName: string | null;
  maintenanceScheduleDetail: string | null;
  modified: Date | null;
  modifiedBy: string | null;
  name: string | null;
  owner: string | null;
  parent: string | null;
  parentfield: string | null;
  parenttype: string | null;
  prevdocDocname: string | null;
  prevdocDoctype: string | null;
  serialNo: string | null;
  servicePerson: string | null;
  updatedAt: Date;
  workDone: string | null;
};
