export type PosClosingEntryUpdateInput = {
  amendedFrom?: string | null;
  company?: string | null;
  creation?: Date | null;
  docStatus?: number | null;
  errorMessage?: string | null;
  grandTotal?: number | null;
  idx?: number | null;
  modified?: Date | null;
  modifiedBy?: string | null;
  name?: string | null;
  netTotal?: number | null;
  owner?: string | null;
  periodEndDate?: Date | null;
  periodStartDate?: Date | null;
  posOpeningEntry?: string | null;
  posProfile?: string | null;
  postingDate?: Date | null;
  postingTime?: Date | null;
  status?: string | null;
  totalQuantity?: number | null;
  user?: string | null;
};
