import { SortOrder } from "../../util/SortOrder";

export type ClreDedVhclOrderByInput = {
  caboNm?: SortOrder;
  carRgsrNo?: SortOrder;
  chssNo?: SortOrder;
  clrNm?: SortOrder;
  createdAt?: SortOrder;
  delYn?: SortOrder;
  dpcmtCn?: SortOrder;
  drvrAddr?: SortOrder;
  drvrNm?: SortOrder;
  drvrPostNo?: SortOrder;
  flKndNm?: SortOrder;
  frstOpraDt?: SortOrder;
  frstRegstId?: SortOrder;
  frstRgsrDttm?: SortOrder;
  id?: SortOrder;
  impPtNm?: SortOrder;
  lastChgDttm?: SortOrder;
  lastChprId?: SortOrder;
  loadWghtCn?: SortOrder;
  mdfyDgcnt?: SortOrder;
  mdlStszNo?: SortOrder;
  mkngYy?: SortOrder;
  otptCn?: SortOrder;
  pdlsNo?: SortOrder;
  reffNo?: SortOrder;
  stcnt?: SortOrder;
  tpdMgmtNo?: SortOrder;
  trsfNnprEndDt?: SortOrder;
  trsfNnprStrtDt?: SortOrder;
  trsfNnprYn?: SortOrder;
  updatedAt?: SortOrder;
  vhclKndCd?: SortOrder;
  vhclKndNm?: SortOrder;
  vhclMdlCd?: SortOrder;
  vhclMnurCd?: SortOrder;
  vhclReleDt?: SortOrder;
  vhclWghtCn?: SortOrder;
};
