import { FloatNullableFilter } from "../../util/FloatNullableFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { DateTimeNullableFilter } from "../../util/DateTimeNullableFilter";
import { StringFilter } from "../../util/StringFilter";
import { IntNullableFilter } from "../../util/IntNullableFilter";

export type ClreDedPrcDclrWhereInput = {
  adcstBrkgAmt?: FloatNullableFilter;
  adcstCnsmCmdtCst?: FloatNullableFilter;
  adcstCtnrPckgCst?: FloatNullableFilter;
  adcstImpPortInfeeAmt?: FloatNullableFilter;
  adcstImpPortOtcst?: FloatNullableFilter;
  adcstImpPortTrcgAmt?: FloatNullableFilter;
  adcstMtrlCmpsFtorCst?: FloatNullableFilter;
  adcstPrcsCst?: FloatNullableFilter;
  adcstPuchCmisYn?: StringNullableFilter;
  adcstRyltCst?: FloatNullableFilter;
  adcstSaleCmisYn?: StringNullableFilter;
  adcstSelrRvrsAmt?: FloatNullableFilter;
  adcstTechDgnOtcst?: FloatNullableFilter;
  adcstToolOtcst?: FloatNullableFilter;
  adcstTrnpCst?: FloatNullableFilter;
  aditOpinCn?: StringNullableFilter;
  adtnCstSumAmt?: FloatNullableFilter;
  bfhnDtrmOfdcNo?: StringNullableFilter;
  bfhnDtrmOfdcPblsDt?: StringNullableFilter;
  byerIdfyNo?: StringNullableFilter;
  cputBssDlngPrc?: FloatNullableFilter;
  cputBssIndrAmt?: FloatNullableFilter;
  cputBssSumAmt?: FloatNullableFilter;
  cvntDt?: StringNullableFilter;
  cvntNo?: StringNullableFilter;
  dcerNm?: StringNullableFilter;
  dclrDt?: StringNullableFilter;
  dclrPlcNm?: StringNullableFilter;
  dclrTxPrc?: FloatNullableFilter;
  ddctExpCntyTrifAmt?: FloatNullableFilter;
  ddctOtcst?: FloatNullableFilter;
  ddctOthsApmtAmt?: FloatNullableFilter;
  ddctSumAmt?: FloatNullableFilter;
  ddctTrnpCst?: FloatNullableFilter;
  delYn?: StringNullableFilter;
  dlvrCondCd?: StringNullableFilter;
  frstRegstId?: StringNullableFilter;
  frstRgsrDttm?: DateTimeNullableFilter;
  id?: StringFilter;
  invcNo?: StringNullableFilter;
  invcPblsDt?: StringNullableFilter;
  lastChgDttm?: DateTimeNullableFilter;
  lastChprId?: StringNullableFilter;
  mdfyDgcnt?: IntNullableFilter;
  othsDesc?: StringNullableFilter;
  quesRspn_1Yn?: StringNullableFilter;
  quesRspn_2Yn?: StringNullableFilter;
  quesRspn_3Yn?: StringNullableFilter;
  quesRspn_4Yn?: StringNullableFilter;
  quesRspn_5Yn?: StringNullableFilter;
  quesRspn_6Yn?: StringNullableFilter;
  quesRspn_7Yn?: StringNullableFilter;
  quesRspn_8Yn?: StringNullableFilter;
  reffNo?: StringNullableFilter;
  rstcMtrCn?: StringNullableFilter;
  selrNo?: StringNullableFilter;
};
