/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { GrpcMethod } from "@nestjs/microservices";
import { QuestPoiPointsService } from "../questPoiPoints.service";
import { QuestPoiPointsCreateInput } from "./QuestPoiPointsCreateInput";
import { QuestPoiPointsWhereInput } from "./QuestPoiPointsWhereInput";
import { QuestPoiPointsWhereUniqueInput } from "./QuestPoiPointsWhereUniqueInput";
import { QuestPoiPointsFindManyArgs } from "./QuestPoiPointsFindManyArgs";
import { QuestPoiPointsUpdateInput } from "./QuestPoiPointsUpdateInput";
import { QuestPoiPoints } from "./QuestPoiPoints";

export class QuestPoiPointsGrpcControllerBase {
  constructor(protected readonly service: QuestPoiPointsService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: QuestPoiPoints })
  @GrpcMethod("QuestPoiPointsService", "createQuestPoiPoints")
  async createQuestPoiPoints(
    @common.Body() data: QuestPoiPointsCreateInput
  ): Promise<QuestPoiPoints> {
    return await this.service.createQuestPoiPoints({
      data: data,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [QuestPoiPoints] })
  @ApiNestedQuery(QuestPoiPointsFindManyArgs)
  @GrpcMethod("QuestPoiPointsService", "questPoiPointsItems")
  async questPoiPointsItems(
    @common.Req() request: Request
  ): Promise<QuestPoiPoints[]> {
    const args = plainToClass(QuestPoiPointsFindManyArgs, request.query);
    return this.service.questPoiPointsItems({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: QuestPoiPoints })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @GrpcMethod("QuestPoiPointsService", "questPoiPoints")
  async questPoiPoints(
    @common.Param() params: QuestPoiPointsWhereUniqueInput
  ): Promise<QuestPoiPoints | null> {
    const result = await this.service.questPoiPoints({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: QuestPoiPoints })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @GrpcMethod("QuestPoiPointsService", "updateQuestPoiPoints")
  async updateQuestPoiPoints(
    @common.Param() params: QuestPoiPointsWhereUniqueInput,
    @common.Body() data: QuestPoiPointsUpdateInput
  ): Promise<QuestPoiPoints | null> {
    try {
      return await this.service.updateQuestPoiPoints({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: QuestPoiPoints })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @GrpcMethod("QuestPoiPointsService", "deleteQuestPoiPoints")
  async deleteQuestPoiPoints(
    @common.Param() params: QuestPoiPointsWhereUniqueInput
  ): Promise<QuestPoiPoints | null> {
    try {
      return await this.service.deleteQuestPoiPoints({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
