export type AssetCapitalizationAssetItemCreateInput = {
  asset?: string | null;
  assetName?: string | null;
  assetValue?: number | null;
  costCenter?: string | null;
  creation?: Date | null;
  currentAssetValue?: number | null;
  docstatus?: number | null;
  financeBook?: string | null;
  fixedAssetAccount?: string | null;
  idx?: number | null;
  itemCode?: string | null;
  itemName?: string | null;
  modified?: Date | null;
  modifiedBy?: string | null;
  name?: string | null;
  owner?: string | null;
  parent?: string | null;
  parentfield?: string | null;
  parenttype?: string | null;
};
