export type PosField = {
  createdAt: Date;
  creation: Date | null;
  defaultValue: string | null;
  docStatus: number | null;
  fieldname: string | null;
  fieldtype: string | null;
  id: string;
  idx: number | null;
  label: string | null;
  modified: Date | null;
  modifiedBy: string | null;
  name: string | null;
  options: string | null;
  owner: string | null;
  parent: string | null;
  parentField: string | null;
  parentType: string | null;
  readOnly: number | null;
  reqd: number | null;
  updatedAt: Date;
};
