export type SerialAndBatchBundle = {
  amendedFrom: string | null;
  avgRate: number | null;
  company: string | null;
  createdAt: Date;
  creation: Date | null;
  docstatus: number | null;
  hasBatchNo: number | null;
  hasSerialNo: number | null;
  id: string;
  idx: number | null;
  isCancelled: number | null;
  isRejected: number | null;
  itemCode: string | null;
  itemGroup: string | null;
  itemName: string | null;
  modified: Date | null;
  modifiedBy: string | null;
  name: string | null;
  namingSeries: string | null;
  owner: string | null;
  postingDate: Date | null;
  postingTime: Date | null;
  returnedAgainst: string | null;
  totalAmount: number | null;
  totalQty: number | null;
  typeOfTransaction: string | null;
  updatedAt: Date;
  voucherDetailNo: string | null;
  voucherNo: string | null;
  voucherType: string | null;
  warehouse: string | null;
};
