import { ClientOptions, Transport } from "@nestjs/microservices";
import { ConfigService } from "@nestjs/config";

const configService: ConfigService = new ConfigService();

export const grpcClientOptions: ClientOptions = {
  transport: Transport.GRPC,
  options: {
    package: [
      "business",
      "strength",
      "weakness",
      "opportunity",
      "threat",
      "unit",
      "product",
      "discount",
      "invoice",
      "item",
      "quote",
      "address",
      "order",
      "proposal",
      "configuration",
      "constraint",
      "bundle",
      "process",
      "price",
      "pipeline",
      "contract",
      "feature",
      "option",
      "template",
      "form",
      "currency",
      "industry",
      "relation",
      "customer",
      "deal",
      "catalog",
      "leadsource",
      "lead"
    ],
    protoPath: [
      "src/business/business.proto",
      "src/strength/strength.proto",
      "src/weakness/weakness.proto",
      "src/opportunity/opportunity.proto",
      "src/threat/threat.proto",
      "src/unit/unit.proto",
      "src/product/product.proto",
      "src/discount/discount.proto",
      "src/invoice/invoice.proto",
      "src/item/item.proto",
      "src/quote/quote.proto",
      "src/address/address.proto",
      "src/order/order.proto",
      "src/proposal/proposal.proto",
      "src/configuration/configuration.proto",
      "src/constraint/constraint.proto",
      "src/bundle/bundle.proto",
      "src/process/process.proto",
      "src/price/price.proto",
      "src/pipeline/pipeline.proto",
      "src/contract/contract.proto",
      "src/feature/feature.proto",
      "src/option/option.proto",
      "src/template/template.proto",
      "src/form/form.proto",
      "src/currency/currency.proto",
      "src/industry/industry.proto",
      "src/relation/relation.proto",
      "src/customer/customer.proto",
      "src/deal/deal.proto",
      "src/catalog/catalog.proto",
      "src/leadsource/leadsource.proto",
      "src/lead/lead.proto"
    ],
    url: configService.get<string>("GRPC_CLIENT_URL_PATH"),
  },
};
