export type AssetRepairUpdateInput = {
  actionsPerformed?: string | null;
  amendedFrom?: string | null;
  asset?: string | null;
  assetName?: string | null;
  capitalizeRepairCost?: number | null;
  company?: string | null;
  completionDate?: Date | null;
  costCenter?: string | null;
  creation?: Date | null;
  description?: string | null;
  docstatus?: number | null;
  downtime?: string | null;
  failureDate?: Date | null;
  idx?: number | null;
  increaseInAssetLife?: number | null;
  modified?: Date | null;
  modifiedBy?: string | null;
  name?: string | null;
  namingSeries?: string | null;
  owner?: string | null;
  project?: string | null;
  purchaseInvoice?: string | null;
  repairCost?: number | null;
  repairStatus?: string | null;
  stockConsumption?: number | null;
  totalRepairCost?: number | null;
};
